Mar 21 12:01:08 ansible4 sshd[9280]: Accepted publickey for ansible from 192.168.10.10 port 44888 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:01:08 ansible4 sshd[9280]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:01:10 ansible4 sudo[9498]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-slswubenvvyicjdxlqzrlqbiabsnodlr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367668.3873868-11222-40924905242182/AnsiballZ_setup.py
Mar 21 12:01:10 ansible4 sudo[9498]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:01:10 ansible4 sudo[9498]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:01:11 ansible4 sudo[9498]: pam_unix(sudo:session): session closed for user root
Mar 21 12:01:26 ansible4 sudo[9773]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-swdxypuwwmfxgcjpntxvinwlkelzbodh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367685.0810618-11259-184352364764899/AnsiballZ_setup.py
Mar 21 12:01:26 ansible4 sudo[9773]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:01:26 ansible4 sudo[9773]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:01:27 ansible4 sudo[9773]: pam_unix(sudo:session): session closed for user root
Mar 21 12:01:41 ansible4 sudo[10046]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-heoealuhxretvkjjhekwpzuubewtlbuq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367700.5201523-11294-151437232763660/AnsiballZ_setup.py
Mar 21 12:01:41 ansible4 sudo[10046]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:01:41 ansible4 sudo[10046]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:01:42 ansible4 sudo[10046]: pam_unix(sudo:session): session closed for user root
Mar 21 12:02:42 ansible4 sshd[9284]: Received disconnect from 192.168.10.10 port 44888:11: disconnected by user
Mar 21 12:02:42 ansible4 sshd[9284]: Disconnected from user ansible 192.168.10.10 port 44888
Mar 21 12:02:42 ansible4 sshd[9280]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:02:43 ansible4 sshd[10157]: Accepted publickey for ansible from 192.168.10.10 port 49428 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:02:43 ansible4 sshd[10157]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:02:44 ansible4 sudo[10374]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rxfrpocoqpoyburrqqkkchlhraciuwti ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367763.3979301-11408-181225234765482/AnsiballZ_setup.py
Mar 21 12:02:44 ansible4 sudo[10374]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:02:44 ansible4 sudo[10374]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:02:45 ansible4 sudo[10374]: pam_unix(sudo:session): session closed for user root
Mar 21 12:03:45 ansible4 sshd[10159]: Received disconnect from 192.168.10.10 port 49428:11: disconnected by user
Mar 21 12:03:45 ansible4 sshd[10159]: Disconnected from user ansible 192.168.10.10 port 49428
Mar 21 12:03:45 ansible4 sshd[10157]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:06:12 ansible4 sshd[10545]: Accepted publickey for ansible from 192.168.10.10 port 47868 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:06:12 ansible4 sshd[10545]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:06:13 ansible4 sudo[10762]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zfocukejlnfrlchvhejztivaxsqkbkfa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367972.1571586-11640-142465518837465/AnsiballZ_setup.py
Mar 21 12:06:13 ansible4 sudo[10762]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:06:13 ansible4 sudo[10762]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:06:14 ansible4 sudo[10762]: pam_unix(sudo:session): session closed for user root
Mar 21 12:06:15 ansible4 sudo[10980]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-thikvoydtigiwrlxyxohijgybpxrnrjc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679367974.1981456-11657-210352458770222/AnsiballZ_dnf.py
Mar 21 12:06:15 ansible4 sudo[10980]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:06:15 ansible4 sudo[10980]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:06:21 ansible4 sudo[10980]: pam_unix(sudo:session): session closed for user root
Mar 21 12:07:22 ansible4 sshd[10547]: Received disconnect from 192.168.10.10 port 47868:11: disconnected by user
Mar 21 12:07:22 ansible4 sshd[10547]: Disconnected from user ansible 192.168.10.10 port 47868
Mar 21 12:07:22 ansible4 sshd[10545]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:08:47 ansible4 sshd[11208]: Accepted publickey for ansible from 192.168.10.10 port 44970 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:08:47 ansible4 sshd[11208]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:08:48 ansible4 sudo[11425]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cblgyeijchsoengzhaddeehooklliwyw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368127.1482687-11870-23211033059623/AnsiballZ_setup.py
Mar 21 12:08:48 ansible4 sudo[11425]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:08:48 ansible4 sudo[11425]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:08:49 ansible4 sudo[11425]: pam_unix(sudo:session): session closed for user root
Mar 21 12:08:50 ansible4 sudo[11642]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jueowrmfgazxbfwkfhhiymddclsimbwc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368129.2073991-11887-95720637604930/AnsiballZ_dnf.py
Mar 21 12:08:50 ansible4 sudo[11642]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:08:50 ansible4 sudo[11642]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:08:53 ansible4 sudo[11642]: pam_unix(sudo:session): session closed for user root
Mar 21 12:08:54 ansible4 sudo[11817]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vybgtzzggupemzuzjylpplmwxpxoxavk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368133.4469986-11896-186175043906949/AnsiballZ_systemd.py
Mar 21 12:08:54 ansible4 sudo[11817]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:08:54 ansible4 sudo[11817]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:08:55 ansible4 sudo[11817]: pam_unix(sudo:session): session closed for user root
Mar 21 12:08:55 ansible4 sudo[11995]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wnusetxiqjhrnwequbhklsgznyioyxul ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368134.9126272-11896-68815387264579/AnsiballZ_systemd.py
Mar 21 12:08:55 ansible4 sudo[11995]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:08:55 ansible4 sudo[11995]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:08:56 ansible4 sudo[11995]: pam_unix(sudo:session): session closed for user root
Mar 21 12:09:56 ansible4 sshd[11210]: Received disconnect from 192.168.10.10 port 44970:11: disconnected by user
Mar 21 12:09:56 ansible4 sshd[11210]: Disconnected from user ansible 192.168.10.10 port 44970
Mar 21 12:09:56 ansible4 sshd[11208]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:14:59 ansible4 sshd[12180]: Accepted publickey for ansible from 192.168.10.10 port 54296 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:14:59 ansible4 sshd[12180]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:15:00 ansible4 sudo[12392]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vnnegbfjfjfevdibafvugqbfyjbiuros ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368498.977838-12300-99522535786863/AnsiballZ_setup.py
Mar 21 12:15:00 ansible4 sudo[12392]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:00 ansible4 sudo[12392]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:01 ansible4 sudo[12392]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:02 ansible4 sudo[12616]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xjsnpjtsehzalouvgvxduqmzfzewqnxg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368501.0552719-12320-239102738126818/AnsiballZ_dnf.py
Mar 21 12:15:02 ansible4 sudo[12616]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:02 ansible4 sudo[12616]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:05 ansible4 sudo[12616]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:06 ansible4 sudo[12793]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tjxmqczzmujjqctmbqxddjndxflidzsy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368505.1270916-12335-268538620806165/AnsiballZ_systemd.py
Mar 21 12:15:06 ansible4 sudo[12793]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:06 ansible4 sudo[12793]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:06 ansible4 sudo[12793]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:07 ansible4 sudo[12971]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pldbgowgwsvdbtbrrgndmgfxsnairgjd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368506.4402878-12335-138495856688222/AnsiballZ_systemd.py
Mar 21 12:15:07 ansible4 sudo[12971]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:07 ansible4 sudo[12971]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:07 ansible4 sudo[12971]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:08 ansible4 sudo[13149]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qwnsvgzbmedqyyiwuakaftcoiaphulwo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368507.434854-12351-222290637507017/AnsiballZ_file.py
Mar 21 12:15:08 ansible4 sudo[13149]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:08 ansible4 sudo[13149]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:08 ansible4 sudo[13149]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:09 ansible4 sudo[13323]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yimaxrtsvykmvycjdosvsujiwxzpybdr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368508.351329-12351-155239003561333/AnsiballZ_file.py
Mar 21 12:15:09 ansible4 sudo[13323]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:09 ansible4 sudo[13323]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:09 ansible4 sudo[13323]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:14 ansible4 sudo[13552]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bifujgrqgyysroxhsveztgugwbhgpdbk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368513.0269704-12392-240991561608931/AnsiballZ_setup.py
Mar 21 12:15:14 ansible4 sudo[13552]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:14 ansible4 sudo[13552]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:15 ansible4 sudo[13552]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:16 ansible4 sudo[13770]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hzqgpwbteaccaizkkajhysamddsudbtd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368515.0812862-12405-82963080218563/AnsiballZ_dnf.py
Mar 21 12:15:16 ansible4 sudo[13770]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:16 ansible4 sudo[13770]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:19 ansible4 sudo[13770]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:20 ansible4 sudo[13945]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sfeftvmuumrpxfqlbbrxgpuncpstpybk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368519.0203342-12414-208710818832558/AnsiballZ_systemd.py
Mar 21 12:15:20 ansible4 sudo[13945]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:20 ansible4 sudo[13945]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:20 ansible4 sudo[13945]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:21 ansible4 sudo[14123]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wpnbwumjqbxgwxbwgijohnkwbhhbdxfs ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368520.3330038-12414-146061774102842/AnsiballZ_systemd.py
Mar 21 12:15:21 ansible4 sudo[14123]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:21 ansible4 sudo[14123]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:21 ansible4 sudo[14123]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:22 ansible4 sudo[14301]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ngwkhpvfzjsjdgjwefedplyxvestjqyq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368521.2869828-12430-116977256452043/AnsiballZ_file.py
Mar 21 12:15:22 ansible4 sudo[14301]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:22 ansible4 sudo[14301]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:22 ansible4 sudo[14301]: pam_unix(sudo:session): session closed for user root
Mar 21 12:15:22 ansible4 sudo[14475]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jsvgpddabiykzogvwsktzhejbbfkzqom ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368522.1941013-12430-25861536507215/AnsiballZ_file.py
Mar 21 12:15:22 ansible4 sudo[14475]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:15:22 ansible4 sudo[14475]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:15:23 ansible4 sudo[14475]: pam_unix(sudo:session): session closed for user root
Mar 21 12:16:23 ansible4 sshd[12182]: Received disconnect from 192.168.10.10 port 54296:11: disconnected by user
Mar 21 12:16:23 ansible4 sshd[12182]: Disconnected from user ansible 192.168.10.10 port 54296
Mar 21 12:16:23 ansible4 sshd[12180]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:21:55 ansible4 sshd[14653]: Accepted publickey for ansible from 192.168.10.10 port 40078 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:21:55 ansible4 sshd[14653]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:21:56 ansible4 sudo[14870]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lexoxafjggfdrpvzncqsptdthtsgwvpo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368914.9958277-12839-260372648168100/AnsiballZ_setup.py
Mar 21 12:21:56 ansible4 sudo[14870]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:21:56 ansible4 sudo[14870]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:21:57 ansible4 sudo[14870]: pam_unix(sudo:session): session closed for user root
Mar 21 12:21:57 ansible4 sudo[15091]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xzdyonnqyfzxioluzwfkssggwfahtigg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368917.0459578-12856-53780831100356/AnsiballZ_dnf.py
Mar 21 12:21:57 ansible4 sudo[15091]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:21:57 ansible4 sudo[15091]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:01 ansible4 sudo[15091]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:02 ansible4 sudo[15282]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mqqqymhmfxeotaoetzzdpaylzbapmzop ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368921.407824-12869-175607500610553/AnsiballZ_systemd.py
Mar 21 12:22:02 ansible4 sudo[15282]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:02 ansible4 sudo[15282]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:02 ansible4 sudo[15282]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:03 ansible4 sudo[15460]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-smppxpusvkcdfitozwfidljphtwyvwqb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368922.7484286-12869-276322132077114/AnsiballZ_systemd.py
Mar 21 12:22:03 ansible4 sudo[15460]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:03 ansible4 sudo[15460]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:03 ansible4 sudo[15460]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:04 ansible4 sudo[15640]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dykgxwphxixnhnptghjtmsfmltruzqfl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368923.7268965-12887-190812395011999/AnsiballZ_file.py
Mar 21 12:22:04 ansible4 sudo[15640]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:04 ansible4 sudo[15640]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:04 ansible4 sudo[15640]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:05 ansible4 sudo[15814]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jwplagdwkcfcqqvczsbwmrufjitgthzj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368924.639167-12887-220958596383274/AnsiballZ_file.py
Mar 21 12:22:05 ansible4 sudo[15814]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:05 ansible4 sudo[15814]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:05 ansible4 sudo[15814]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:06 ansible4 sudo[15988]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-inrkeebnctovgcrofkaxmtdfoucdpncq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368925.4086409-12907-25735845324696/AnsiballZ_stat.py
Mar 21 12:22:06 ansible4 sudo[15988]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:06 ansible4 sudo[15988]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:06 ansible4 sudo[15988]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:07 ansible4 sudo[16130]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xthjamxuqosreeorwldhijmcfqucawha ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368925.4086409-12907-25735845324696/AnsiballZ_copy.py
Mar 21 12:22:07 ansible4 sudo[16130]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:07 ansible4 sudo[16130]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:07 ansible4 sudo[16130]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:07 ansible4 sudo[16306]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ljdisulzlrumtdjwopzvaqiippvkbgne ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368927.187857-12907-17414384678214/AnsiballZ_stat.py
Mar 21 12:22:07 ansible4 sudo[16306]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:07 ansible4 sudo[16306]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:08 ansible4 sudo[16306]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:08 ansible4 sudo[16448]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ezjynbogksapwrojslxbdrfdebziksvy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368927.187857-12907-17414384678214/AnsiballZ_copy.py
Mar 21 12:22:08 ansible4 sudo[16448]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:08 ansible4 sudo[16448]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:08 ansible4 sudo[16448]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:09 ansible4 sudo[16624]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ewkwhdpqqtufxecltkewhsymhrqjcymk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368928.5764656-12907-110976567071508/AnsiballZ_stat.py
Mar 21 12:22:09 ansible4 sudo[16624]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:09 ansible4 sudo[16624]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:09 ansible4 sudo[16624]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:09 ansible4 sudo[16768]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nasrdlymsymhntfttsmxptpiyquuuwii ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368928.5764656-12907-110976567071508/AnsiballZ_copy.py
Mar 21 12:22:09 ansible4 sudo[16768]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:09 ansible4 sudo[16768]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:10 ansible4 sudo[16768]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:14 ansible4 sudo[16999]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tayvlilwbysvdmwvrqqeszkbhllxohox ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368932.7806857-12966-122951543447767/AnsiballZ_setup.py
Mar 21 12:22:14 ansible4 sudo[16999]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:14 ansible4 sudo[16999]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:14 ansible4 sudo[16999]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:15 ansible4 sudo[17217]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ybfbadizebdeuaewbypeyszremrgxqty ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368934.8286564-12979-199011448943877/AnsiballZ_dnf.py
Mar 21 12:22:15 ansible4 sudo[17217]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:15 ansible4 sudo[17217]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:18 ansible4 sudo[17217]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:19 ansible4 sudo[17392]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ifwjeukrscddbtaanyzlccnvjoaajcby ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368938.7915866-12988-31487669619933/AnsiballZ_systemd.py
Mar 21 12:22:19 ansible4 sudo[17392]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:19 ansible4 sudo[17392]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:20 ansible4 sudo[17392]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:20 ansible4 sudo[17570]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-huemzuezweiuvtynxlochivnxjnctmaz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368940.1321876-12988-85559727003433/AnsiballZ_systemd.py
Mar 21 12:22:20 ansible4 sudo[17570]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:20 ansible4 sudo[17570]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:21 ansible4 sudo[17570]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:22 ansible4 sudo[17748]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wrbfbduxvqkxauhcuxrtswjhyaueznhi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368941.1141212-13004-38983397050151/AnsiballZ_file.py
Mar 21 12:22:22 ansible4 sudo[17748]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:22 ansible4 sudo[17748]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:22 ansible4 sudo[17748]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:22 ansible4 sudo[17922]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-takdqoumfyflqteaurhiahpzzgujwbmr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368942.0278678-13004-2805625117312/AnsiballZ_file.py
Mar 21 12:22:22 ansible4 sudo[17922]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:22 ansible4 sudo[17922]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:22 ansible4 sudo[17922]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:23 ansible4 sudo[18096]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cwpxtgixgciqjxhevatlaiumnlxczstr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368942.8173614-13020-145226394513219/AnsiballZ_stat.py
Mar 21 12:22:23 ansible4 sudo[18096]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:23 ansible4 sudo[18096]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:23 ansible4 sudo[18096]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:24 ansible4 sudo[18187]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vgsdugkhfgqsylggdyviqsbngrpswkxk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368942.8173614-13020-145226394513219/AnsiballZ_file.py
Mar 21 12:22:24 ansible4 sudo[18187]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:24 ansible4 sudo[18187]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:24 ansible4 sudo[18187]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:24 ansible4 sudo[18361]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hplhvfelplwtunetgxdgyhhztwzgrkzv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368944.2412508-13020-187429041508216/AnsiballZ_stat.py
Mar 21 12:22:24 ansible4 sudo[18361]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:24 ansible4 sudo[18361]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:25 ansible4 sudo[18361]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:25 ansible4 sudo[18452]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vxkmprtlupnnxtthldurpystvxfnqjhx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368944.2412508-13020-187429041508216/AnsiballZ_file.py
Mar 21 12:22:25 ansible4 sudo[18452]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:25 ansible4 sudo[18452]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:25 ansible4 sudo[18452]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:26 ansible4 sudo[18626]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mxfigshivmxhdwbhfwfleikhrliabjav ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368945.4771774-13020-220272285266552/AnsiballZ_stat.py
Mar 21 12:22:26 ansible4 sudo[18626]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:26 ansible4 sudo[18626]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:26 ansible4 sudo[18626]: pam_unix(sudo:session): session closed for user root
Mar 21 12:22:26 ansible4 sudo[18717]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ephgwfqndunayaldmgltxnyofqlujpqc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679368945.4771774-13020-220272285266552/AnsiballZ_file.py
Mar 21 12:22:26 ansible4 sudo[18717]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:22:26 ansible4 sudo[18717]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:22:26 ansible4 sudo[18717]: pam_unix(sudo:session): session closed for user root
Mar 21 12:23:27 ansible4 sshd[14655]: Received disconnect from 192.168.10.10 port 40078:11: disconnected by user
Mar 21 12:23:27 ansible4 sshd[14655]: Disconnected from user ansible 192.168.10.10 port 40078
Mar 21 12:23:27 ansible4 sshd[14653]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:25:24 ansible4 sshd[18826]: Accepted publickey for ansible from 192.168.10.10 port 53260 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:25:24 ansible4 sshd[18826]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:25:25 ansible4 sudo[19052]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uebdqkexlsjjebzapvgvbupfnqgvugkh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369124.3028831-13307-156687754652982/AnsiballZ_setup.py
Mar 21 12:25:25 ansible4 sudo[19052]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:25 ansible4 sudo[19052]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:26 ansible4 sudo[19052]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:27 ansible4 sudo[19269]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-guehgeurvdvobbbxerpyjrjfdaxaxbia ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369126.3578014-13324-100982729036945/AnsiballZ_dnf.py
Mar 21 12:25:27 ansible4 sudo[19269]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:27 ansible4 sudo[19269]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:30 ansible4 sudo[19269]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:31 ansible4 sudo[19444]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zdjztibozysngcdacllhhurddwybuyqd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369130.693552-13341-221708978994711/AnsiballZ_systemd.py
Mar 21 12:25:31 ansible4 sudo[19444]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:31 ansible4 sudo[19444]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:32 ansible4 sudo[19444]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:32 ansible4 sudo[19622]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zvbwdusktwuevyawpbvnlxxtzvpkgffc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369132.035739-13341-101313258781139/AnsiballZ_systemd.py
Mar 21 12:25:32 ansible4 sudo[19622]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:32 ansible4 sudo[19622]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:33 ansible4 sudo[19622]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:33 ansible4 sudo[19800]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jtqmpkanybeiayqtswqlfzfgjcnuhimq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369133.0098255-13358-43308188259605/AnsiballZ_file.py
Mar 21 12:25:33 ansible4 sudo[19800]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:33 ansible4 sudo[19800]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:34 ansible4 sudo[19800]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:34 ansible4 sudo[19974]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-apfdgdtuwcjgduivokpvdkumaviojawv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369133.9283516-13358-207744367404844/AnsiballZ_file.py
Mar 21 12:25:34 ansible4 sudo[19974]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:34 ansible4 sudo[19974]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:34 ansible4 sudo[19974]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:35 ansible4 sudo[20148]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajwwlcgcgivkriipxxxsrkrzxpucvzqy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369134.7184377-13374-50368700612223/AnsiballZ_stat.py
Mar 21 12:25:35 ansible4 sudo[20148]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:35 ansible4 sudo[20148]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:35 ansible4 sudo[20148]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:36 ansible4 sudo[20239]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jtnjthkzdgwiyrimeiayprlznzlgxqvu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369134.7184377-13374-50368700612223/AnsiballZ_file.py
Mar 21 12:25:36 ansible4 sudo[20239]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:36 ansible4 sudo[20239]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:36 ansible4 sudo[20239]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:36 ansible4 sudo[20413]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-atoowqlbnsvskzvtibexgorakeqwuqlu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369136.1409595-13374-245317410878640/AnsiballZ_stat.py
Mar 21 12:25:36 ansible4 sudo[20413]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:36 ansible4 sudo[20413]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:37 ansible4 sudo[20413]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:37 ansible4 sudo[20504]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-drpgzuhzorafjblyntlllcfivrmqswaz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369136.1409595-13374-245317410878640/AnsiballZ_file.py
Mar 21 12:25:37 ansible4 sudo[20504]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:37 ansible4 sudo[20504]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:37 ansible4 sudo[20504]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:38 ansible4 sudo[20678]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-anypxcuubmnlzbcqjhqhqqnzvdjtpemq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369137.3425026-13374-236119063829775/AnsiballZ_stat.py
Mar 21 12:25:38 ansible4 sudo[20678]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:38 ansible4 sudo[20678]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:38 ansible4 sudo[20678]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:38 ansible4 sudo[20769]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-igmofxjmrjfiyhtewazkzlsupgafgdlz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369137.3425026-13374-236119063829775/AnsiballZ_file.py
Mar 21 12:25:38 ansible4 sudo[20769]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:38 ansible4 sudo[20769]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:38 ansible4 sudo[20769]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:39 ansible4 sudo[20943]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gnxiykyhyznhpxszozencfjblxqfvrdb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369138.591361-13409-53791645993886/AnsiballZ_stat.py
Mar 21 12:25:39 ansible4 sudo[20943]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:39 ansible4 sudo[20943]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:39 ansible4 sudo[20943]: pam_unix(sudo:session): session closed for user root
Mar 21 12:25:39 ansible4 sudo[21034]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lrylmfmzbeaksbgowirjqlvaennyfpda ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369138.591361-13409-53791645993886/AnsiballZ_file.py
Mar 21 12:25:39 ansible4 sudo[21034]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:25:39 ansible4 sudo[21034]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:25:40 ansible4 sudo[21034]: pam_unix(sudo:session): session closed for user root
Mar 21 12:26:40 ansible4 sshd[18828]: Received disconnect from 192.168.10.10 port 53260:11: disconnected by user
Mar 21 12:26:40 ansible4 sshd[18828]: Disconnected from user ansible 192.168.10.10 port 53260
Mar 21 12:26:40 ansible4 sshd[18826]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:32:06 ansible4 sshd[21233]: Accepted publickey for ansible from 192.168.10.10 port 48938 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:32:06 ansible4 sshd[21233]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:32:07 ansible4 sudo[21450]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iifshcqljghxtkirgkvolcuptnhnszcn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369526.4990487-13788-81028511349897/AnsiballZ_setup.py
Mar 21 12:32:07 ansible4 sudo[21450]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:07 ansible4 sudo[21450]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:08 ansible4 sudo[21450]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:09 ansible4 sudo[21669]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-txrzzzzneyruudjqzoqrfdewzprjhjdq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369528.5896218-13805-123276956458873/AnsiballZ_dnf.py
Mar 21 12:32:09 ansible4 sudo[21669]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:09 ansible4 sudo[21669]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:12 ansible4 sudo[21669]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:13 ansible4 sudo[21844]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hjilwldznvunpmrgkimpjqltjkjbevqo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369532.681412-13818-143299644833043/AnsiballZ_systemd.py
Mar 21 12:32:13 ansible4 sudo[21844]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:13 ansible4 sudo[21844]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:14 ansible4 sudo[21844]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:14 ansible4 sudo[22022]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wgbznegowbvhozgksdfhwyzxfsbherxy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369534.0001009-13818-168657810076809/AnsiballZ_systemd.py
Mar 21 12:32:14 ansible4 sudo[22022]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:14 ansible4 sudo[22022]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:15 ansible4 sudo[22022]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:15 ansible4 sudo[22200]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wxmjmmafbyrjyjvdssupqzwoyuafdijg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369534.9704807-13834-216236758710191/AnsiballZ_file.py
Mar 21 12:32:15 ansible4 sudo[22200]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:15 ansible4 sudo[22200]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:16 ansible4 sudo[22200]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:16 ansible4 sudo[22374]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-igwwkgxsijtwhbumnmmzuowilahdtfyq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369535.9040287-13834-263366561971575/AnsiballZ_file.py
Mar 21 12:32:16 ansible4 sudo[22374]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:16 ansible4 sudo[22374]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:16 ansible4 sudo[22374]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:17 ansible4 sudo[22548]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-koqsofwnuiwsyndfoatbiuhcryofgdhq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369536.67365-13850-267902409890834/AnsiballZ_stat.py
Mar 21 12:32:17 ansible4 sudo[22548]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:17 ansible4 sudo[22548]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:17 ansible4 sudo[22548]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:18 ansible4 sudo[22639]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yjlvktgvbpqphewnhfhuxpfhcnhmmspd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369536.67365-13850-267902409890834/AnsiballZ_file.py
Mar 21 12:32:18 ansible4 sudo[22639]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:18 ansible4 sudo[22639]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:18 ansible4 sudo[22639]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:18 ansible4 sudo[22813]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fcfwrsmnwywvqqpxjqtfwzogwjnkkfod ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369538.1026778-13850-244044364155802/AnsiballZ_stat.py
Mar 21 12:32:18 ansible4 sudo[22813]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:18 ansible4 sudo[22813]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:19 ansible4 sudo[22813]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:19 ansible4 sudo[22904]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nrxcekhvcnviyjccacqtlfoxksijuzph ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369538.1026778-13850-244044364155802/AnsiballZ_file.py
Mar 21 12:32:19 ansible4 sudo[22904]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:19 ansible4 sudo[22904]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:19 ansible4 sudo[22904]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:20 ansible4 sudo[23078]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wjwsqznvdnaoobziejopjykhzfktyxbf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369539.3217785-13850-30395320928775/AnsiballZ_stat.py
Mar 21 12:32:20 ansible4 sudo[23078]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:20 ansible4 sudo[23078]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:20 ansible4 sudo[23078]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:20 ansible4 sudo[23169]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tysdagqujjzkmvvsrndtsthecknvsjex ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369539.3217785-13850-30395320928775/AnsiballZ_file.py
Mar 21 12:32:20 ansible4 sudo[23169]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:20 ansible4 sudo[23169]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:20 ansible4 sudo[23169]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:21 ansible4 sudo[23343]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iymaiwefrrjettskxqgbjxwqawbhxcwn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369540.597711-13885-242319393452375/AnsiballZ_stat.py
Mar 21 12:32:21 ansible4 sudo[23343]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:21 ansible4 sudo[23343]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:21 ansible4 sudo[23343]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:21 ansible4 sudo[23434]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-oqpvslshanikgkyorsjqobgxcosspqhi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369540.597711-13885-242319393452375/AnsiballZ_file.py
Mar 21 12:32:21 ansible4 sudo[23434]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:21 ansible4 sudo[23434]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:22 ansible4 sudo[23434]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:22 ansible4 sudo[23608]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sqcfpkdtqcruacibnallohioruruhkvr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369541.8568325-13898-156493006407617/AnsiballZ_firewalld.py
Mar 21 12:32:22 ansible4 sudo[23608]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:22 ansible4 sudo[23608]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:23 ansible4 sudo[23608]: pam_unix(sudo:session): session closed for user root
Mar 21 12:32:23 ansible4 sudo[23782]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kfauxtjuzqatmwaujjixdcyimokhycth ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369543.198153-13898-201595823217203/AnsiballZ_firewalld.py
Mar 21 12:32:23 ansible4 sudo[23782]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:32:23 ansible4 sudo[23782]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:32:24 ansible4 sudo[23782]: pam_unix(sudo:session): session closed for user root
Mar 21 12:33:24 ansible4 sshd[21235]: Received disconnect from 192.168.10.10 port 48938:11: disconnected by user
Mar 21 12:33:24 ansible4 sshd[21235]: Disconnected from user ansible 192.168.10.10 port 48938
Mar 21 12:33:24 ansible4 sshd[21233]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:39:02 ansible4 sshd[23975]: Accepted publickey for ansible from 192.168.10.10 port 46930 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:39:02 ansible4 sshd[23975]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:39:03 ansible4 sudo[24205]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-atocjffuahpjellwpnutuuiemhricncf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369941.8561034-14253-29190801331796/AnsiballZ_setup.py
Mar 21 12:39:03 ansible4 sudo[24205]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:03 ansible4 sudo[24205]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:04 ansible4 sudo[24205]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:04 ansible4 sudo[24425]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cdhfvmrolbsbvwrggniwrdtqckmsawcu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369943.9641268-14272-4141777836470/AnsiballZ_dnf.py
Mar 21 12:39:04 ansible4 sudo[24425]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:04 ansible4 sudo[24425]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:08 ansible4 sudo[24425]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:09 ansible4 sudo[24602]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qqchrrtowjipcwmhwccvkfehntjatycu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369948.074185-14285-231234423191907/AnsiballZ_systemd.py
Mar 21 12:39:09 ansible4 sudo[24602]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:09 ansible4 sudo[24602]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:09 ansible4 sudo[24602]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:10 ansible4 sudo[24780]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-afisspbywtfdwfzfvfnqvsnhvxrirkre ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369949.4112594-14285-260118984833809/AnsiballZ_systemd.py
Mar 21 12:39:10 ansible4 sudo[24780]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:10 ansible4 sudo[24780]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:10 ansible4 sudo[24780]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:11 ansible4 sudo[24958]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-udfgenkwjbvgcxbhzmtwexpqnunnivqd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369950.402563-14303-256764306761727/AnsiballZ_file.py
Mar 21 12:39:11 ansible4 sudo[24958]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:11 ansible4 sudo[24958]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:11 ansible4 sudo[24958]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:12 ansible4 sudo[25132]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rmxxdwlhlbrmrzlbgnouszjegmtzwzml ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369951.3351185-14303-278811523095786/AnsiballZ_file.py
Mar 21 12:39:12 ansible4 sudo[25132]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:12 ansible4 sudo[25132]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:12 ansible4 sudo[25132]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:13 ansible4 sudo[25306]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-byhuuyvralehlouvvlbhcjuogavbkmqq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369952.1130931-14319-120218307638035/AnsiballZ_stat.py
Mar 21 12:39:13 ansible4 sudo[25306]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:13 ansible4 sudo[25306]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:13 ansible4 sudo[25306]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:13 ansible4 sudo[25397]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tjjyemaoddokmcguzeywpwbvyiaebhoz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369952.1130931-14319-120218307638035/AnsiballZ_file.py
Mar 21 12:39:13 ansible4 sudo[25397]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:13 ansible4 sudo[25397]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:13 ansible4 sudo[25397]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:14 ansible4 sudo[25571]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bhtyyyqullzfxunpvlndantbmeuilxuo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369953.556657-14319-50602232838453/AnsiballZ_stat.py
Mar 21 12:39:14 ansible4 sudo[25571]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:14 ansible4 sudo[25571]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:14 ansible4 sudo[25571]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:14 ansible4 sudo[25662]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jjcztjdrwhunsluzmlovpgmzolbogngw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369953.556657-14319-50602232838453/AnsiballZ_file.py
Mar 21 12:39:14 ansible4 sudo[25662]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:14 ansible4 sudo[25662]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:14 ansible4 sudo[25662]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:15 ansible4 sudo[25836]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lqfvsnuiojqiwitojeeyljtammhnywsb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369954.796541-14319-123458132807090/AnsiballZ_stat.py
Mar 21 12:39:15 ansible4 sudo[25836]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:15 ansible4 sudo[25836]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:15 ansible4 sudo[25836]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:16 ansible4 sudo[25927]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ukynmdabmyprpqqdbttmpmbdyixoheih ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369954.796541-14319-123458132807090/AnsiballZ_file.py
Mar 21 12:39:16 ansible4 sudo[25927]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:16 ansible4 sudo[25927]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:16 ansible4 sudo[25927]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:16 ansible4 sudo[26101]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-djwpubiqyxgjkmqakukhcmvvbaeuvfnl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369956.0492568-14356-64938362877343/AnsiballZ_stat.py
Mar 21 12:39:16 ansible4 sudo[26101]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:16 ansible4 sudo[26101]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:16 ansible4 sudo[26101]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:17 ansible4 sudo[26192]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fdnudprgtkphvxdqlnvkxetmvnbeoxmh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369956.0492568-14356-64938362877343/AnsiballZ_file.py
Mar 21 12:39:17 ansible4 sudo[26192]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:17 ansible4 sudo[26192]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:17 ansible4 sudo[26192]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:18 ansible4 sudo[26366]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-btilzlnpzkkvttqvugsefgrulzkkbgsj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369957.3441713-14370-235263292642315/AnsiballZ_firewalld.py
Mar 21 12:39:18 ansible4 sudo[26366]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:18 ansible4 sudo[26366]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:18 ansible4 sudo[26366]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:19 ansible4 sudo[26540]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tzppiybbyjjdtqrgdsgsxfscxohxiqvb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369958.6084402-14370-159323055446560/AnsiballZ_firewalld.py
Mar 21 12:39:19 ansible4 sudo[26540]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:19 ansible4 sudo[26540]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:19 ansible4 sudo[26540]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:53 ansible4 sudo[26769]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qyhvcxfoukywcelxrzirsigntfkypurl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369991.939309-14405-242130587308426/AnsiballZ_setup.py
Mar 21 12:39:53 ansible4 sudo[26769]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:53 ansible4 sudo[26769]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:54 ansible4 sudo[26769]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:54 ansible4 sudo[26986]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bkepfxlfdozfjvyekhokwyckuslkbtyv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369993.994866-14418-44503731748647/AnsiballZ_dnf.py
Mar 21 12:39:54 ansible4 sudo[26986]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:54 ansible4 sudo[26986]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:58 ansible4 sudo[26986]: pam_unix(sudo:session): session closed for user root
Mar 21 12:39:59 ansible4 sudo[27171]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cqjtyczwibspeyoyjgpreeueiuqjsqil ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369998.0644925-14427-19419908270187/AnsiballZ_systemd.py
Mar 21 12:39:59 ansible4 sudo[27171]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:39:59 ansible4 sudo[27171]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:39:59 ansible4 sudo[27171]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:00 ansible4 sudo[27349]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cekxtndhqgszpcalxzonugtdocpmjied ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679369999.3944688-14427-278081859890602/AnsiballZ_systemd.py
Mar 21 12:40:00 ansible4 sudo[27349]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:00 ansible4 sudo[27349]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:00 ansible4 sudo[27349]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:01 ansible4 sudo[27529]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajgubsupvbkfieyipshtdyhgsfqillnf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370000.398631-14445-161858217444715/AnsiballZ_file.py
Mar 21 12:40:01 ansible4 sudo[27529]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:01 ansible4 sudo[27529]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:01 ansible4 sudo[27529]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:02 ansible4 sudo[27705]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bnujozhrikrrohazoodtappyrxhoeown ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370001.3444111-14445-182034552287523/AnsiballZ_file.py
Mar 21 12:40:02 ansible4 sudo[27705]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:02 ansible4 sudo[27705]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:02 ansible4 sudo[27705]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:03 ansible4 sudo[27883]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jdjenjekfgpeorprkabodnpvijwzhiit ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370002.1290102-14463-7582960015045/AnsiballZ_stat.py
Mar 21 12:40:03 ansible4 sudo[27883]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:03 ansible4 sudo[27883]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:03 ansible4 sudo[27883]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:03 ansible4 sudo[27974]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-itzxctikgocrpduhvweopmbgitpkjgtw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370002.1290102-14463-7582960015045/AnsiballZ_file.py
Mar 21 12:40:03 ansible4 sudo[27974]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:03 ansible4 sudo[27974]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:03 ansible4 sudo[27974]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:04 ansible4 sudo[28148]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xnbjemyovwjdcdwierjtmgtdcwujgnlh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370003.5469918-14463-128879986457584/AnsiballZ_stat.py
Mar 21 12:40:04 ansible4 sudo[28148]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:04 ansible4 sudo[28148]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:04 ansible4 sudo[28148]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:04 ansible4 sudo[28239]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rirmjpxsrqxiuiygeerbtlamnoaaxpuw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370003.5469918-14463-128879986457584/AnsiballZ_file.py
Mar 21 12:40:04 ansible4 sudo[28239]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:04 ansible4 sudo[28239]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:04 ansible4 sudo[28239]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:05 ansible4 sudo[28415]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-krmatcvapadjigjpyjcwtelgifhmlyxo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370004.797285-14463-263338447963832/AnsiballZ_stat.py
Mar 21 12:40:05 ansible4 sudo[28415]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:05 ansible4 sudo[28415]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:05 ansible4 sudo[28415]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:05 ansible4 sudo[28506]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-eptmlmpnvhsfyrolbixttbwnqyywyedi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370004.797285-14463-263338447963832/AnsiballZ_file.py
Mar 21 12:40:05 ansible4 sudo[28506]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:05 ansible4 sudo[28506]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:06 ansible4 sudo[28506]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:06 ansible4 sudo[28680]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-oniffezecnsonnnysuhtpuuqnmnxaigj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370006.0521748-14504-236176687413561/AnsiballZ_stat.py
Mar 21 12:40:06 ansible4 sudo[28680]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:06 ansible4 sudo[28680]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:07 ansible4 sudo[28680]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:07 ansible4 sudo[28771]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mngfvkpnruluarhkfgnxgxsoexvuncrf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370006.0521748-14504-236176687413561/AnsiballZ_file.py
Mar 21 12:40:07 ansible4 sudo[28771]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:07 ansible4 sudo[28771]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:07 ansible4 sudo[28771]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:08 ansible4 sudo[28945]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mjcarbleiyaxxjeapwwahbcquodnfhxv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370007.3728127-14517-30578559063629/AnsiballZ_firewalld.py
Mar 21 12:40:08 ansible4 sudo[28945]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:08 ansible4 sudo[28945]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:08 ansible4 sudo[28945]: pam_unix(sudo:session): session closed for user root
Mar 21 12:40:09 ansible4 sudo[29119]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fngwcyjaugzajbhssyqalayhhhrcavkg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370008.6385667-14517-198016094293895/AnsiballZ_firewalld.py
Mar 21 12:40:09 ansible4 sudo[29119]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:40:09 ansible4 sudo[29119]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:40:09 ansible4 sudo[29119]: pam_unix(sudo:session): session closed for user root
Mar 21 12:41:10 ansible4 sshd[23979]: Received disconnect from 192.168.10.10 port 46930:11: disconnected by user
Mar 21 12:41:10 ansible4 sshd[23979]: Disconnected from user ansible 192.168.10.10 port 46930
Mar 21 12:41:10 ansible4 sshd[23975]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:42:38 ansible4 sshd[29216]: Accepted publickey for ansible from 192.168.10.10 port 51756 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:42:38 ansible4 sshd[29216]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:43:08 ansible4 sudo[29309]: ansible : TTY=pts/0 ; PWD=/etc/pki/tls/private ; USER=root ; COMMAND=/bin/rm -f localhost.key
Mar 21 12:43:08 ansible4 sudo[29309]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:08 ansible4 sudo[29309]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:08 ansible4 sudo[29309]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:19 ansible4 sshd[29218]: Received disconnect from 192.168.10.10 port 51756:11: disconnected by user
Mar 21 12:43:19 ansible4 sshd[29218]: Disconnected from user ansible 192.168.10.10 port 51756
Mar 21 12:43:19 ansible4 sshd[29216]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:43:25 ansible4 sshd[29345]: Accepted publickey for ansible from 192.168.10.10 port 47962 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:43:25 ansible4 sshd[29345]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:43:26 ansible4 sudo[29562]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yexdibynolmmgkwkxdevgkdhbanriczi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370205.1571565-14696-157572751693533/AnsiballZ_setup.py
Mar 21 12:43:26 ansible4 sudo[29562]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:26 ansible4 sudo[29562]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:27 ansible4 sudo[29562]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:28 ansible4 sudo[29779]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lpewajisjbwnpmtodhlngsyzdtpjxslr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370207.2413573-14713-61812587233213/AnsiballZ_dnf.py
Mar 21 12:43:28 ansible4 sudo[29779]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:28 ansible4 sudo[29779]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:31 ansible4 sudo[29779]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:32 ansible4 sudo[29954]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uwmkzioxrrzepbuoqxbmtqydttmvxzua ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370211.3854322-14730-143048899694455/AnsiballZ_systemd.py
Mar 21 12:43:32 ansible4 sudo[29954]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:32 ansible4 sudo[29954]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:32 ansible4 sudo[29954]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:33 ansible4 sudo[30132]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hkhowrjzzbqypoqfhcfflqvdnnlovnnz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370212.694417-14730-14864319201719/AnsiballZ_systemd.py
Mar 21 12:43:33 ansible4 sudo[30132]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:33 ansible4 sudo[30132]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:33 ansible4 sudo[30132]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:34 ansible4 sudo[30310]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ygcwjaelbkvmnfqgsaydlcjchshutbxo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370213.660937-14746-38096848744806/AnsiballZ_file.py
Mar 21 12:43:34 ansible4 sudo[30310]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:34 ansible4 sudo[30310]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:34 ansible4 sudo[30310]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:35 ansible4 sudo[30484]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kzkocvfktsxftoolxdrxnufpbqtypput ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370214.5827057-14746-214887288365277/AnsiballZ_file.py
Mar 21 12:43:35 ansible4 sudo[30484]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:35 ansible4 sudo[30484]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:35 ansible4 sudo[30484]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:36 ansible4 sudo[30658]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zzyhbbvjzjnyxeshtzxbjfjepnlvxcij ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370215.3628147-14762-186912090975606/AnsiballZ_stat.py
Mar 21 12:43:36 ansible4 sudo[30658]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:36 ansible4 sudo[30658]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:36 ansible4 sudo[30658]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:36 ansible4 sudo[30749]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iiffamxaccbyhvbzmbemsggfugawgzqc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370215.3628147-14762-186912090975606/AnsiballZ_file.py
Mar 21 12:43:36 ansible4 sudo[30749]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:36 ansible4 sudo[30749]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:36 ansible4 sudo[30749]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:37 ansible4 sudo[30923]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hnmejdkzibtzelxrfvvmuytjngkbufxm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370216.7694051-14762-218592911642901/AnsiballZ_stat.py
Mar 21 12:43:37 ansible4 sudo[30923]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:37 ansible4 sudo[30923]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:37 ansible4 sudo[30923]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:38 ansible4 sudo[31065]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lgpwzwfrexrlghlmzheravykxflpjtlk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370216.7694051-14762-218592911642901/AnsiballZ_copy.py
Mar 21 12:43:38 ansible4 sudo[31065]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:38 ansible4 sudo[31065]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:38 ansible4 sudo[31065]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:39 ansible4 sudo[31241]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vavyholpiwayjufjqolzzmtffqddlzjm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370218.3801472-14762-28810652560920/AnsiballZ_stat.py
Mar 21 12:43:39 ansible4 sudo[31241]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:39 ansible4 sudo[31241]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:39 ansible4 sudo[31241]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:39 ansible4 sudo[31332]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xjfidirkhclbmzkhyjcarhasfyczfxfn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370218.3801472-14762-28810652560920/AnsiballZ_file.py
Mar 21 12:43:39 ansible4 sudo[31332]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:39 ansible4 sudo[31332]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:39 ansible4 sudo[31332]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:40 ansible4 sudo[31506]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cmwoavowjfwmfggicslpermcnexlxyuv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370219.6546767-14800-23046561229669/AnsiballZ_stat.py
Mar 21 12:43:40 ansible4 sudo[31506]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:40 ansible4 sudo[31506]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:40 ansible4 sudo[31506]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:40 ansible4 sudo[31597]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xpyvvjkfqwcpvasqmdvqmozrwqhfqpfp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370219.6546767-14800-23046561229669/AnsiballZ_file.py
Mar 21 12:43:40 ansible4 sudo[31597]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:40 ansible4 sudo[31597]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:41 ansible4 sudo[31597]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:41 ansible4 sudo[31771]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-excegruuxyvtfwxfyejbzejmkrqksgfa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370220.9236102-14813-23035367711175/AnsiballZ_firewalld.py
Mar 21 12:43:41 ansible4 sudo[31771]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:41 ansible4 sudo[31771]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:42 ansible4 sudo[31771]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:42 ansible4 sudo[31945]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lefxashqjvpctvkqwfzxhqzzgtemfjiw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370222.2340965-14813-82123723533433/AnsiballZ_firewalld.py
Mar 21 12:43:42 ansible4 sudo[31945]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:42 ansible4 sudo[31945]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:43 ansible4 sudo[31945]: pam_unix(sudo:session): session closed for user root
Mar 21 12:43:44 ansible4 sudo[32119]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rgrjakinsuttdympwkgezsiubudzbbnt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679370223.3378122-14829-77189026949648/AnsiballZ_systemd.py
Mar 21 12:43:44 ansible4 sudo[32119]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:43:44 ansible4 sudo[32119]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:43:44 ansible4 sudo[32119]: pam_unix(sudo:session): session closed for user root
Mar 21 12:44:44 ansible4 sshd[29347]: Received disconnect from 192.168.10.10 port 47962:11: disconnected by user
Mar 21 12:44:44 ansible4 sshd[29347]: Disconnected from user ansible 192.168.10.10 port 47962
Mar 21 12:44:44 ansible4 sshd[29345]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:45:31 ansible4 sshd[32210]: Accepted publickey for ansible from 192.168.10.10 port 47062 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:45:31 ansible4 sshd[32210]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:46:03 ansible4 sshd[32212]: Received disconnect from 192.168.10.10 port 47062:11: disconnected by user
Mar 21 12:46:03 ansible4 sshd[32212]: Disconnected from user ansible 192.168.10.10 port 47062
Mar 21 12:46:03 ansible4 sshd[32210]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:47:37 ansible4 sshd[32326]: Accepted publickey for ansible from 192.168.10.10 port 56968 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 12:47:37 ansible4 sshd[32326]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:47:53 ansible4 sudo[32407]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/firewall-cmd --list-all
Mar 21 12:47:53 ansible4 sudo[32407]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 12:47:53 ansible4 sudo[32407]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 12:47:53 ansible4 sudo[32407]: pam_unix(sudo:session): session closed for user root
Mar 21 12:49:23 ansible4 sudo[32454]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/bash
Mar 21 12:49:23 ansible4 sudo[32454]: pam_systemd(sudo-i:session): Cannot create session: Already running in a session or user slice
Mar 21 12:49:23 ansible4 sudo[32454]: pam_unix(sudo-i:session): session opened for user root by ansible(uid=0)
Mar 21 13:14:37 ansible4 sudo[32454]: pam_unix(sudo-i:session): session closed for user root
Mar 21 13:14:41 ansible4 sshd[32328]: Received disconnect from 192.168.10.10 port 56968:11: disconnected by user
Mar 21 13:14:41 ansible4 sshd[32328]: Disconnected from user ansible 192.168.10.10 port 56968
Mar 21 13:14:41 ansible4 sshd[32326]: pam_unix(sshd:session): session closed for user ansible
Mar 21 13:23:16 ansible4 sshd[33465]: Accepted publickey for ansible from 192.168.10.10 port 50362 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 13:23:16 ansible4 sshd[33465]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 13:23:17 ansible4 sudo[33682]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bslbovkkiozhiseloznldllhpqtftxnd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679372595.981629-17379-204536658572964/AnsiballZ_setup.py
Mar 21 13:23:17 ansible4 sudo[33682]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 13:23:17 ansible4 sudo[33682]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 13:23:18 ansible4 sudo[33682]: pam_unix(sudo:session): session closed for user root
Mar 21 13:24:10 ansible4 sudo[33977]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xiahktlpatjnrqbnddiepppunelsdfzu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679372648.8809142-17454-68614504300291/AnsiballZ_setup.py
Mar 21 13:24:10 ansible4 sudo[33977]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 13:24:10 ansible4 sudo[33977]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 13:24:11 ansible4 sudo[33977]: pam_unix(sudo:session): session closed for user root
Mar 21 13:25:11 ansible4 sshd[33467]: Received disconnect from 192.168.10.10 port 50362:11: disconnected by user
Mar 21 13:25:11 ansible4 sshd[33467]: Disconnected from user ansible 192.168.10.10 port 50362
Mar 21 13:25:11 ansible4 sshd[33465]: pam_unix(sshd:session): session closed for user ansible
Mar 21 14:15:58 ansible4 sshd[35138]: Accepted publickey for ansible from 192.168.10.10 port 52420 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 14:15:58 ansible4 sshd[35138]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 14:15:59 ansible4 sudo[35356]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qktepjufhjrwjasxzagztloaehjktlih ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375757.926329-18807-137813116427206/AnsiballZ_firewalld.py
Mar 21 14:15:59 ansible4 sudo[35356]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:15:59 ansible4 sudo[35356]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:15:59 ansible4 sudo[35356]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:00 ansible4 sudo[35530]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-beghgbugifujuasszmcjurcnstrdnawn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375759.3952467-18807-244177813904713/AnsiballZ_firewalld.py
Mar 21 14:16:00 ansible4 sudo[35530]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:00 ansible4 sudo[35530]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:00 ansible4 sudo[35530]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:01 ansible4 sudo[35712]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jssfigfdndrrkyctbubhphbjcoejymsu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375760.485887-18829-53848054768757/AnsiballZ_file.py
Mar 21 14:16:01 ansible4 sudo[35712]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:01 ansible4 sudo[35712]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:01 ansible4 sudo[35712]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:02 ansible4 sudo[35886]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-stjbmususqgygioqtsloidcpjqessxwo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375761.461741-18838-148526300576205/AnsiballZ_setup.py
Mar 21 14:16:02 ansible4 sudo[35886]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:02 ansible4 sudo[35886]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:02 ansible4 sudo[35886]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:03 ansible4 sudo[35981]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kvydfbbrezruvikrpxarqqdlwzqnwbjx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375761.461741-18838-148526300576205/AnsiballZ_systemd.py
Mar 21 14:16:03 ansible4 sudo[35981]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:03 ansible4 sudo[35981]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:03 ansible4 sudo[35981]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:38 ansible4 sudo[36225]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-klpvgupmmigzhrqtrdkcrsqvzypgmrib ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375796.5617473-19241-46281191045296/AnsiballZ_firewalld.py
Mar 21 14:16:38 ansible4 sudo[36225]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:38 ansible4 sudo[36225]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:38 ansible4 sudo[36225]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:40 ansible4 sudo[36399]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nagcweojczgmyrfmlcrkikwezctjjkgn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375799.0272977-19241-185018389375991/AnsiballZ_firewalld.py
Mar 21 14:16:40 ansible4 sudo[36399]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:40 ansible4 sudo[36399]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:41 ansible4 sudo[36399]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:42 ansible4 sudo[36573]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sfahrtsgdvdgdyjbrwuxfmjjjtsorvms ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375801.50919-19282-264374814352194/AnsiballZ_file.py
Mar 21 14:16:42 ansible4 sudo[36573]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:42 ansible4 sudo[36573]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:43 ansible4 sudo[36573]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:44 ansible4 sudo[36747]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wdopczbsyttzzpdhgwfhcjigaeozjwcz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375803.1008482-19298-111036867915159/AnsiballZ_setup.py
Mar 21 14:16:44 ansible4 sudo[36747]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:44 ansible4 sudo[36747]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:44 ansible4 sudo[36747]: pam_unix(sudo:session): session closed for user root
Mar 21 14:16:45 ansible4 sudo[36842]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-brbloxwemxxzzkpdhvwnunbbicptahgq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679375803.1008482-19298-111036867915159/AnsiballZ_systemd.py
Mar 21 14:16:45 ansible4 sudo[36842]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:16:45 ansible4 sudo[36842]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:16:45 ansible4 sudo[36842]: pam_unix(sudo:session): session closed for user root
Mar 21 14:17:46 ansible4 sshd[35140]: Received disconnect from 192.168.10.10 port 52420:11: disconnected by user
Mar 21 14:17:46 ansible4 sshd[35140]: Disconnected from user ansible 192.168.10.10 port 52420
Mar 21 14:17:46 ansible4 sshd[35138]: pam_unix(sshd:session): session closed for user ansible
Mar 21 14:27:13 ansible4 sshd[37123]: Accepted publickey for ansible from 192.168.10.10 port 37632 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 14:27:13 ansible4 sshd[37123]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 14:27:14 ansible4 sudo[37343]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-txfazvqetejnsdzuezzsesdemsjslkpv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376433.401886-20097-278366775567144/AnsiballZ_firewalld.py
Mar 21 14:27:14 ansible4 sudo[37343]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:27:14 ansible4 sudo[37343]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:27:15 ansible4 sudo[37343]: pam_unix(sudo:session): session closed for user root
Mar 21 14:27:15 ansible4 sudo[37517]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dlokaizzlmlrcanjycgxmsekwqjjhwiz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376434.8659527-20097-214447135376575/AnsiballZ_firewalld.py
Mar 21 14:27:15 ansible4 sudo[37517]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:27:15 ansible4 sudo[37517]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:27:16 ansible4 sudo[37517]: pam_unix(sudo:session): session closed for user root
Mar 21 14:27:16 ansible4 sudo[37691]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qdshcrjniosugktnqfsotvegbhfnawjh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376435.944597-20123-94942350810685/AnsiballZ_file.py
Mar 21 14:27:16 ansible4 sudo[37691]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:27:16 ansible4 sudo[37691]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:27:17 ansible4 sudo[37691]: pam_unix(sudo:session): session closed for user root
Mar 21 14:27:18 ansible4 sudo[37865]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-usedbwlkuzzvxzcybkoqtnphppntijbx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376436.8847485-20132-196837127712869/AnsiballZ_setup.py
Mar 21 14:27:18 ansible4 sudo[37865]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:27:18 ansible4 sudo[37865]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:27:18 ansible4 sudo[37865]: pam_unix(sudo:session): session closed for user root
Mar 21 14:27:19 ansible4 sudo[37960]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jkovdbsigftxmsgjswilsotaslhjjyka ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376436.8847485-20132-196837127712869/AnsiballZ_systemd.py
Mar 21 14:27:19 ansible4 sudo[37960]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:27:19 ansible4 sudo[37960]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:27:19 ansible4 sudo[37960]: pam_unix(sudo:session): session closed for user root
Mar 21 14:28:09 ansible4 sudo[38204]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gwtzbhazgjofcglyniviyglajqqupgbf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376488.080821-20221-96584786601678/AnsiballZ_firewalld.py
Mar 21 14:28:09 ansible4 sudo[38204]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:28:09 ansible4 sudo[38204]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:28:09 ansible4 sudo[38204]: pam_unix(sudo:session): session closed for user root
Mar 21 14:28:10 ansible4 sudo[38380]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-asnmlngwbhevopibolqbwnyamoqzehar ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376489.511399-20221-9347658448687/AnsiballZ_firewalld.py
Mar 21 14:28:10 ansible4 sudo[38380]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:28:10 ansible4 sudo[38380]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:28:10 ansible4 sudo[38380]: pam_unix(sudo:session): session closed for user root
Mar 21 14:28:11 ansible4 sudo[38558]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qvomusbmrdyfrsjlwnqlywtubdwvsqiw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376490.5972688-20241-2433665359919/AnsiballZ_file.py
Mar 21 14:28:11 ansible4 sudo[38558]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:28:11 ansible4 sudo[38558]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:28:11 ansible4 sudo[38558]: pam_unix(sudo:session): session closed for user root
Mar 21 14:28:12 ansible4 sudo[38732]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lttmvnxfforhsirovmhehznundwdiymy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376491.5535352-20250-193103415117933/AnsiballZ_setup.py
Mar 21 14:28:12 ansible4 sudo[38732]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:28:12 ansible4 sudo[38732]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:28:13 ansible4 sudo[38732]: pam_unix(sudo:session): session closed for user root
Mar 21 14:28:13 ansible4 sudo[38827]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-okokewsbqnuzssotxryfelcchyujniet ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679376491.5535352-20250-193103415117933/AnsiballZ_systemd.py
Mar 21 14:28:13 ansible4 sudo[38827]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:28:13 ansible4 sudo[38827]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:28:14 ansible4 sudo[38827]: pam_unix(sudo:session): session closed for user root
Mar 21 14:29:14 ansible4 sshd[37127]: Received disconnect from 192.168.10.10 port 37632:11: disconnected by user
Mar 21 14:29:14 ansible4 sshd[37127]: Disconnected from user ansible 192.168.10.10 port 37632
Mar 21 14:29:14 ansible4 sshd[37123]: pam_unix(sshd:session): session closed for user ansible
Mar 21 14:56:27 ansible4 sshd[39476]: Accepted publickey for ansible from 192.168.10.10 port 58442 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 14:56:27 ansible4 sshd[39476]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 14:56:30 ansible4 sudo[39694]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-swlpywimocwwftaplltbsgokywuhmlgp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378187.4199615-21706-55486389602625/AnsiballZ_setup.py
Mar 21 14:56:30 ansible4 sudo[39694]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:56:30 ansible4 sudo[39694]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:56:31 ansible4 sudo[39694]: pam_unix(sudo:session): session closed for user root
Mar 21 14:56:33 ansible4 sudo[39912]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uooiioxtaoisowqivxklzfcxkwktpjyw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378192.0925646-21773-95997143460717/AnsiballZ_dnf.py
Mar 21 14:56:33 ansible4 sudo[39912]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:56:33 ansible4 sudo[39912]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:56:45 ansible4 groupadd[39932]: group added to /etc/group: name=mysql, GID=27
Mar 21 14:56:45 ansible4 groupadd[39932]: group added to /etc/gshadow: name=mysql
Mar 21 14:56:45 ansible4 groupadd[39932]: new group: name=mysql, GID=27
Mar 21 14:56:46 ansible4 useradd[39938]: new user: name=mysql, UID=27, GID=27, home=/var/lib/mysql, shell=/sbin/nologin
Mar 21 14:56:57 ansible4 sudo[39912]: pam_unix(sudo:session): session closed for user root
Mar 21 14:56:58 ansible4 sudo[40835]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ohklmrjjvnqnugxssmomkjqevtdzcjri ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378217.7169688-21773-140088625391776/AnsiballZ_dnf.py
Mar 21 14:56:58 ansible4 sudo[40835]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:56:58 ansible4 sudo[40835]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:05 ansible4 sudo[40835]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:15 ansible4 sudo[41075]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nzuhprmcchrpfmejazidevakgspalilm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378233.4012344-21850-174548137560665/AnsiballZ_get_url.py
Mar 21 14:57:15 ansible4 sudo[41075]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:15 ansible4 sudo[41075]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:16 ansible4 sudo[41075]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:18 ansible4 sudo[41253]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ryckpidsgbkibywwdnciscrxekwbdfqv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378236.703851-21893-155629635227712/AnsiballZ_get_url.py
Mar 21 14:57:18 ansible4 sudo[41253]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:18 ansible4 sudo[41253]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:18 ansible4 sudo[41253]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:20 ansible4 sudo[41429]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ciindmqsrcbakefypcstrbydhjapsvul ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378239.2764444-21930-66707034106598/AnsiballZ_stat.py
Mar 21 14:57:20 ansible4 sudo[41429]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:20 ansible4 sudo[41429]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:21 ansible4 sudo[41429]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:22 ansible4 sudo[41573]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bbkgriqbmzhkndpkdiollsikuwceldik ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378239.2764444-21930-66707034106598/AnsiballZ_copy.py
Mar 21 14:57:22 ansible4 sudo[41573]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:22 ansible4 sudo[41573]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:23 ansible4 sudo[41573]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:24 ansible4 sudo[41749]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lumsebwnwnjslynladyvfvsfgqxskxrv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378243.249705-21998-263169013762940/AnsiballZ_stat.py
Mar 21 14:57:24 ansible4 sudo[41749]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:24 ansible4 sudo[41749]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:25 ansible4 sudo[41749]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:26 ansible4 sudo[41893]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gsccjhaefwhzfjjksjkabmfopznfbfvl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378243.249705-21998-263169013762940/AnsiballZ_copy.py
Mar 21 14:57:26 ansible4 sudo[41893]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:26 ansible4 sudo[41893]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:26 ansible4 sudo[41893]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:28 ansible4 sudo[42069]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yebvalgsiotjchilcvboqifmgqnxpsyz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378246.9828482-22061-84437195520341/AnsiballZ_systemd.py
Mar 21 14:57:28 ansible4 sudo[42069]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:28 ansible4 sudo[42069]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:33 ansible4 sudo[42069]: pam_unix(sudo:session): session closed for user root
Mar 21 14:58:33 ansible4 sshd[39478]: Received disconnect from 192.168.10.10 port 58442:11: disconnected by user
Mar 21 14:58:33 ansible4 sshd[39478]: Disconnected from user ansible 192.168.10.10 port 58442
Mar 21 14:58:33 ansible4 sshd[39476]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:02:47 ansible4 sshd[42434]: Accepted publickey for ansible from 192.168.10.10 port 53010 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:02:47 ansible4 sshd[42434]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:02:49 ansible4 sudo[42660]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jdxwjhicgvzmwlroutergiomkncxydob ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378567.653767-22504-31440938559428/AnsiballZ_setup.py
Mar 21 15:02:49 ansible4 sudo[42660]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:02:49 ansible4 sudo[42660]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:02:51 ansible4 sudo[42660]: pam_unix(sudo:session): session closed for user root
Mar 21 15:02:52 ansible4 sudo[42879]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yazqrtoqyufolrnircwbxhmujgprmnnu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378571.6313887-22564-103166118972902/AnsiballZ_dnf.py
Mar 21 15:02:52 ansible4 sudo[42879]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:02:52 ansible4 sudo[42879]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:02:56 ansible4 sudo[42879]: pam_unix(sudo:session): session closed for user root
Mar 21 15:02:57 ansible4 sudo[43054]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lsocdrhvdkvortfntmhzndmdynjwsmss ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378576.3161237-22564-252308110529357/AnsiballZ_dnf.py
Mar 21 15:02:57 ansible4 sudo[43054]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:02:57 ansible4 sudo[43054]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:03:01 ansible4 sudo[43054]: pam_unix(sudo:session): session closed for user root
Mar 21 15:03:02 ansible4 sudo[43237]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ecozphbdugcojzawdxpxrfdtqhnwvtxm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378581.0335531-22600-66343783271777/AnsiballZ_get_url.py
Mar 21 15:03:02 ansible4 sudo[43237]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:03:02 ansible4 sudo[43237]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:03:02 ansible4 sudo[43237]: pam_unix(sudo:session): session closed for user root
Mar 21 15:03:03 ansible4 sudo[43413]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ynyursyfqvbgjzohunalnaweernudcyu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378582.6669974-22622-83720964029422/AnsiballZ_get_url.py
Mar 21 15:03:03 ansible4 sudo[43413]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:03:03 ansible4 sudo[43413]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:03:04 ansible4 sudo[43413]: pam_unix(sudo:session): session closed for user root
Mar 21 15:03:05 ansible4 sudo[43589]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tooamvkxyqzgevhkqkrhxfrowdfnnbfw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378584.2077322-22644-152619128607575/AnsiballZ_stat.py
Mar 21 15:03:05 ansible4 sudo[43589]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:03:05 ansible4 sudo[43589]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:03:05 ansible4 sudo[43589]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:02 ansible4 sudo[43806]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tcyvmxzshsiqomxaduprbkboaegoseqh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378639.4518673-22734-219465106826623/AnsiballZ_setup.py
Mar 21 15:04:02 ansible4 sudo[43806]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:02 ansible4 sudo[43806]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:03 ansible4 sudo[43806]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:05 ansible4 sudo[44032]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ihwbwqkcwtdnqadqddnlwcbvkombkwtq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378644.292277-22785-248521591852162/AnsiballZ_dnf.py
Mar 21 15:04:05 ansible4 sudo[44032]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:05 ansible4 sudo[44032]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:08 ansible4 sudo[44032]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:09 ansible4 sudo[44207]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ilnnyzubtlngjvzmiujabfzmgftlfnmj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378648.6983156-22785-82614293757608/AnsiballZ_dnf.py
Mar 21 15:04:09 ansible4 sudo[44207]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:09 ansible4 sudo[44207]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:12 ansible4 sudo[44207]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:13 ansible4 sudo[44392]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-epogsebxigdxylhylzxmojbmtiqhxnfk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378652.9232478-22826-74934202694010/AnsiballZ_get_url.py
Mar 21 15:04:13 ansible4 sudo[44392]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:13 ansible4 sudo[44392]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:14 ansible4 sudo[44392]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:15 ansible4 sudo[44568]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ewmkrbstrjucmddxikescwoualtydvln ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378654.4307818-22850-165347563823327/AnsiballZ_stat.py
Mar 21 15:04:15 ansible4 sudo[44568]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:15 ansible4 sudo[44568]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:15 ansible4 sudo[44568]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:16 ansible4 sudo[44714]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-prbhdngufabjbvszglgvyiauyazjepan ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378654.4307818-22850-165347563823327/AnsiballZ_copy.py
Mar 21 15:04:16 ansible4 sudo[44714]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:16 ansible4 sudo[44714]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:16 ansible4 sudo[44714]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:16 ansible4 sshd[42436]: Received disconnect from 192.168.10.10 port 53010:11: disconnected by user
Mar 21 15:05:16 ansible4 sshd[42436]: Disconnected from user ansible 192.168.10.10 port 53010
Mar 21 15:05:16 ansible4 sshd[42434]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:05:47 ansible4 sshd[44792]: Accepted publickey for ansible from 192.168.10.10 port 39140 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:05:48 ansible4 sshd[44792]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:05:50 ansible4 sudo[45001]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gpqafyxulpqtxcedpmuceuclnovwqipu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378748.02985-22941-218145272146340/AnsiballZ_setup.py
Mar 21 15:05:50 ansible4 sudo[45001]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:50 ansible4 sudo[45001]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:51 ansible4 sudo[45001]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:52 ansible4 sudo[45218]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bybylrhgpdgpwotjntpfrzqsvhhmguxl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378751.927952-23002-52236603260913/AnsiballZ_dnf.py
Mar 21 15:05:52 ansible4 sudo[45218]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:52 ansible4 sudo[45218]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:56 ansible4 sudo[45218]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:57 ansible4 sudo[45393]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ccdczkpgbqjvdaazieoopslpfegsihds ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378756.4459245-23002-64243759400082/AnsiballZ_dnf.py
Mar 21 15:05:57 ansible4 sudo[45393]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:57 ansible4 sudo[45393]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:00 ansible4 sudo[45393]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:01 ansible4 sudo[45568]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wvllzplkvwhiqcojshhlzykachdaujja ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378760.7092938-23038-9005472831350/AnsiballZ_get_url.py
Mar 21 15:06:01 ansible4 sudo[45568]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:06:01 ansible4 sudo[45568]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:02 ansible4 sudo[45568]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:03 ansible4 sudo[45752]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dbocojfzqoalzlnxdhvkiofzayhkmvoa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378762.213466-23060-20700940740125/AnsiballZ_stat.py
Mar 21 15:06:03 ansible4 sudo[45752]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:06:03 ansible4 sudo[45752]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:03 ansible4 sudo[45752]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:04 ansible4 sudo[45843]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kvevqppiobchabkchalyafkwoqzwdznu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378762.213466-23060-20700940740125/AnsiballZ_file.py
Mar 21 15:06:04 ansible4 sudo[45843]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:06:04 ansible4 sudo[45843]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:04 ansible4 sudo[45843]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:32 ansible4 sudo[46084]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ckijkdxciixmwluvjlmnhxqdiqmkzmof ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378791.7505968-23130-159082619360212/AnsiballZ_command.py
Mar 21 15:06:32 ansible4 sudo[46084]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:06:32 ansible4 sudo[46084]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:33 ansible4 sudo[46084]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:37 ansible4 sudo[46314]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lccphdlrbmtqaiwszmxbxarfcwtxuqkg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378795.8478768-23163-72085307812792/AnsiballZ_command.py
Mar 21 15:06:37 ansible4 sudo[46314]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:06:37 ansible4 sudo[46314]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:06:37 ansible4 sudo[46314]: pam_unix(sudo:session): session closed for user root
Mar 21 15:07:37 ansible4 sshd[44794]: Received disconnect from 192.168.10.10 port 39140:11: disconnected by user
Mar 21 15:07:37 ansible4 sshd[44794]: Disconnected from user ansible 192.168.10.10 port 39140
Mar 21 15:07:37 ansible4 sshd[44792]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:13:13 ansible4 sshd[46499]: Accepted publickey for ansible from 192.168.10.10 port 53950 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:13:13 ansible4 sshd[46499]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:13:15 ansible4 sudo[46714]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xfevcfanszhseyejmndiuuajyislzrlr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379192.9442923-23680-139096305275642/AnsiballZ_setup.py
Mar 21 15:13:15 ansible4 sudo[46714]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:15 ansible4 sudo[46714]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:16 ansible4 sudo[46714]: pam_unix(sudo:session): session closed for user root
Mar 21 15:13:18 ansible4 sudo[46934]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-eepmenbryleswwnwhypwgtfykzepxkqg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379197.117398-23745-150876901795227/AnsiballZ_command.py
Mar 21 15:13:18 ansible4 sudo[46934]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:18 ansible4 sudo[46934]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:19 ansible4 sudo[46934]: pam_unix(sudo:session): session closed for user root
Mar 21 15:13:43 ansible4 sudo[47164]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tomujojduqxqyxqzqxvsatfshwyxatyb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379220.8460605-23806-202783161643488/AnsiballZ_command.py
Mar 21 15:13:43 ansible4 sudo[47164]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:43 ansible4 sudo[47164]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:43 ansible4 sudo[47164]: pam_unix(sudo:session): session closed for user root
Mar 21 15:13:49 ansible4 sudo[47394]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-onijwpdsdvzeexvqlayfefjssarthelb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379227.0798218-23861-171839683929988/AnsiballZ_command.py
Mar 21 15:13:49 ansible4 sudo[47394]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:49 ansible4 sudo[47394]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:49 ansible4 sudo[47394]: pam_unix(sudo:session): session closed for user root
Mar 21 15:14:49 ansible4 sshd[46501]: Received disconnect from 192.168.10.10 port 53950:11: disconnected by user
Mar 21 15:14:49 ansible4 sshd[46501]: Disconnected from user ansible 192.168.10.10 port 53950
Mar 21 15:14:49 ansible4 sshd[46499]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:15:31 ansible4 sshd[47485]: Accepted publickey for ansible from 192.168.10.10 port 39704 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:15:31 ansible4 sshd[47485]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:15:34 ansible4 sudo[47694]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rrzbjjhxthdxrcdpniniozekfljjmrrc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379331.9269621-24027-263829871253706/AnsiballZ_setup.py
Mar 21 15:15:34 ansible4 sudo[47694]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:34 ansible4 sudo[47694]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:35 ansible4 sudo[47694]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:37 ansible4 sudo[47913]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zksprrsbtauhbgkowdlyxyqxpxztmjaw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379335.852566-24096-126366545774102/AnsiballZ_command.py
Mar 21 15:15:37 ansible4 sudo[47913]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:37 ansible4 sudo[47913]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:38 ansible4 sudo[47913]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:40 ansible4 sudo[48088]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gnvivrditojyiztpnheyxdbppysbkdlo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379338.221334-24132-51327591818648/AnsiballZ_systemd.py
Mar 21 15:15:40 ansible4 sudo[48088]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:40 ansible4 sudo[48088]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:42 ansible4 sudo[48088]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:44 ansible4 sudo[48272]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mwccqnbblcrqpuponygkicfwtqumemnh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379342.5087097-24168-100408950805823/AnsiballZ_dnf.py
Mar 21 15:15:44 ansible4 sudo[48272]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:44 ansible4 sudo[48272]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:54 ansible4 sudo[48272]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:08 ansible4 sudo[48946]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pjhvyoxsnewzaitvlnqecdvzmdvkxfru ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379366.8466845-24232-130611656577738/AnsiballZ_setup.py
Mar 21 15:16:08 ansible4 sudo[48946]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:08 ansible4 sudo[48946]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:10 ansible4 sudo[48946]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:12 ansible4 sudo[49167]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vhgqlsbeddgqdepfldxzcreuyxrmsmzp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379370.9493978-24278-271775164337503/AnsiballZ_command.py
Mar 21 15:16:12 ansible4 sudo[49167]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:12 ansible4 sudo[49167]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:12 ansible4 sudo[49167]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:14 ansible4 sudo[49348]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zfdolbwsijvguhqxmvcforxdfrtpmdfe ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379373.0225055-24314-165879882107945/AnsiballZ_systemd.py
Mar 21 15:16:14 ansible4 sudo[49348]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:14 ansible4 sudo[49348]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:15 ansible4 sudo[49348]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:17 ansible4 sudo[49525]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dabhafvfghivkymashduviykxprnahbq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379375.6497457-24355-210490034645318/AnsiballZ_dnf.py
Mar 21 15:16:17 ansible4 sudo[49525]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:17 ansible4 sudo[49525]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:21 ansible4 sudo[49525]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:27 ansible4 sudo[49757]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dfslnascxvgqfzagbtxfglkziosqkorg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379384.7215602-24412-216950599797044/AnsiballZ_setup.py
Mar 21 15:16:27 ansible4 sudo[49757]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:27 ansible4 sudo[49757]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:28 ansible4 sudo[49757]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:29 ansible4 sudo[49974]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mjdoiwvvscgzjssxvcjtuvzzjktltnjs ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379388.6181395-24455-10990945067903/AnsiballZ_dnf.py
Mar 21 15:16:29 ansible4 sudo[49974]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:29 ansible4 sudo[49974]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:34 ansible4 useradd[49985]: failed adding user 'mysql', exit code: 9
Mar 21 15:16:40 ansible4 sudo[49974]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:41 ansible4 sudo[50749]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xbpvolzptofuxcntwdrsdhwhvbsnssvx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379400.5250473-24455-224039694281290/AnsiballZ_dnf.py
Mar 21 15:16:41 ansible4 sudo[50749]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:41 ansible4 sudo[50749]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:46 ansible4 sudo[50749]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:47 ansible4 sudo[50927]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hnxczlekwljkjjtrjshljnsfwjfbemjb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379406.2541919-24503-6267558403933/AnsiballZ_get_url.py
Mar 21 15:16:47 ansible4 sudo[50927]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:47 ansible4 sudo[50927]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:47 ansible4 sudo[50927]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:48 ansible4 sudo[51103]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tmcbnqadjhldrmytblegndkeuqeiyhhd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379407.7561228-24525-114981558381066/AnsiballZ_get_url.py
Mar 21 15:16:48 ansible4 sudo[51103]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:48 ansible4 sudo[51103]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:49 ansible4 sudo[51103]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:50 ansible4 sudo[51279]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wslkmydbabmolabspimxycpbbcvexqfh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379409.1270728-24547-75933652202402/AnsiballZ_stat.py
Mar 21 15:16:50 ansible4 sudo[51279]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:50 ansible4 sudo[51279]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:50 ansible4 sudo[51279]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:51 ansible4 sudo[51423]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lrmmvmdhyytbxhihkkhcqngassjnorqi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379409.1270728-24547-75933652202402/AnsiballZ_copy.py
Mar 21 15:16:51 ansible4 sudo[51423]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:51 ansible4 sudo[51423]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:51 ansible4 sudo[51423]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:52 ansible4 sudo[51599]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kobgdflkqoxbcphdhdakrrokuovupvmr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379411.629675-24583-178489060622309/AnsiballZ_stat.py
Mar 21 15:16:52 ansible4 sudo[51599]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:52 ansible4 sudo[51599]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:52 ansible4 sudo[51599]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:53 ansible4 sudo[51743]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dlwuemnzyuyvmmzyahgjrqgpqujeohzb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379411.629675-24583-178489060622309/AnsiballZ_copy.py
Mar 21 15:16:53 ansible4 sudo[51743]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:53 ansible4 sudo[51743]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:53 ansible4 sudo[51743]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:54 ansible4 sudo[51919]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-slupktqngwrqmaaepjsltxpjftjrriso ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379413.5950308-24615-142920591399972/AnsiballZ_systemd.py
Mar 21 15:16:54 ansible4 sudo[51919]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:16:54 ansible4 sudo[51919]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:16:55 ansible4 sudo[51919]: pam_unix(sudo:session): session closed for user root
Mar 21 15:17:55 ansible4 sshd[47487]: Received disconnect from 192.168.10.10 port 39704:11: disconnected by user
Mar 21 15:17:55 ansible4 sshd[47487]: Disconnected from user ansible 192.168.10.10 port 39704
Mar 21 15:17:55 ansible4 sshd[47485]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:27:48 ansible4 sshd[52323]: Accepted publickey for ansible from 192.168.10.10 port 42802 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:27:48 ansible4 sshd[52323]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:27:51 ansible4 sudo[52540]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hmflqwguhuctaowwkpsggshpeiircnli ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380068.8034217-24924-39917235247473/AnsiballZ_setup.py
Mar 21 15:27:51 ansible4 sudo[52540]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:27:51 ansible4 sudo[52540]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:27:53 ansible4 sudo[52540]: pam_unix(sudo:session): session closed for user root
Mar 21 15:27:55 ansible4 sudo[52758]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ogxagmfpelnrgzotyqqrzmlnebkzsmcm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380073.7731795-24984-81129979292456/AnsiballZ_command.py
Mar 21 15:27:55 ansible4 sudo[52758]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:27:55 ansible4 sudo[52758]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:27:55 ansible4 sudo[52758]: pam_unix(sudo:session): session closed for user root
Mar 21 15:27:57 ansible4 sudo[52933]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tnddxtndmeksukamekcjcmrnyugtnrjv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380075.9128509-25021-59503517702037/AnsiballZ_systemd.py
Mar 21 15:27:57 ansible4 sudo[52933]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:27:57 ansible4 sudo[52933]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:27:59 ansible4 sudo[52933]: pam_unix(sudo:session): session closed for user root
Mar 21 15:28:01 ansible4 sudo[53120]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pzovtyvngkcciqvhhvkiilwhskrolmhv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380079.7641392-25057-61485196485984/AnsiballZ_dnf.py
Mar 21 15:28:01 ansible4 sudo[53120]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:28:01 ansible4 sudo[53120]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:28:08 ansible4 sudo[53120]: pam_unix(sudo:session): session closed for user root
Mar 21 15:29:08 ansible4 sshd[52325]: Received disconnect from 192.168.10.10 port 42802:11: disconnected by user
Mar 21 15:29:08 ansible4 sshd[52325]: Disconnected from user ansible 192.168.10.10 port 42802
Mar 21 15:29:08 ansible4 sshd[52323]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:29:37 ansible4 sshd[53646]: Accepted publickey for ansible from 192.168.10.10 port 49432 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:29:37 ansible4 sshd[53646]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:29:39 ansible4 sudo[53856]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lkxskqfbzslqcipdttefxgdtxuqqfbwx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380177.061104-25150-32781878043618/AnsiballZ_setup.py
Mar 21 15:29:39 ansible4 sudo[53856]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:29:39 ansible4 sudo[53856]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:29:40 ansible4 sudo[53856]: pam_unix(sudo:session): session closed for user root
Mar 21 15:29:42 ansible4 sudo[54073]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fkhhyriuhbbvuniorykmbuwtswqzpjxa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380181.12872-25212-26500036275462/AnsiballZ_command.py
Mar 21 15:29:42 ansible4 sudo[54073]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:29:42 ansible4 sudo[54073]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:29:42 ansible4 sudo[54073]: pam_unix(sudo:session): session closed for user root
Mar 21 15:29:44 ansible4 sudo[54248]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-txvpnrwmecyiluyukfyjfdwxobgczhmb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380183.2219188-25247-255179245069265/AnsiballZ_systemd.py
Mar 21 15:29:44 ansible4 sudo[54248]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:29:44 ansible4 sudo[54248]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:29:45 ansible4 sudo[54248]: pam_unix(sudo:session): session closed for user root
Mar 21 15:29:47 ansible4 sudo[54425]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wgtcuxvbkwifvqwxgqcqkvcqvfomuiji ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380185.6762333-25282-157721174730764/AnsiballZ_dnf.py
Mar 21 15:29:47 ansible4 sudo[54425]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:29:47 ansible4 sudo[54425]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:29:51 ansible4 sudo[54425]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:04 ansible4 sudo[54663]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ptrulzswqrhhowtvkvmauwkriwcvyzri ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380201.9812424-25341-86387884943947/AnsiballZ_setup.py
Mar 21 15:30:04 ansible4 sudo[54663]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:04 ansible4 sudo[54663]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:05 ansible4 sudo[54663]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:06 ansible4 sudo[54881]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xvciwiwrfgwnhbfqzeqhdydtflqpljxy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380205.936376-25386-51456096213877/AnsiballZ_dnf.py
Mar 21 15:30:06 ansible4 sudo[54881]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:06 ansible4 sudo[54881]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:11 ansible4 useradd[54894]: failed adding user 'mysql', exit code: 9
Mar 21 15:30:17 ansible4 sudo[54881]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:17 ansible4 sudo[55666]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mvnqpvpfreraywlmbcjzvfmjumhegpyw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380216.9804764-25386-226441338146246/AnsiballZ_dnf.py
Mar 21 15:30:17 ansible4 sudo[55666]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:17 ansible4 sudo[55666]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:22 ansible4 sudo[55666]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:23 ansible4 sudo[55846]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-joqgsuegofitbaurwhlzfxovzkmdlfdh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380222.572748-25434-244851612413217/AnsiballZ_get_url.py
Mar 21 15:30:23 ansible4 sudo[55846]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:23 ansible4 sudo[55846]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:24 ansible4 sudo[55846]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:24 ansible4 sudo[56022]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hpklqigemfexveuobhnkgijwyryfobza ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380224.057769-25456-36213110199071/AnsiballZ_get_url.py
Mar 21 15:30:24 ansible4 sudo[56022]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:24 ansible4 sudo[56022]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:25 ansible4 sudo[56022]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:26 ansible4 sudo[56198]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-egtyseygdhwhybxqjawqhcihaebtdezk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380225.3230498-25480-184995856679243/AnsiballZ_stat.py
Mar 21 15:30:26 ansible4 sudo[56198]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:26 ansible4 sudo[56198]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:26 ansible4 sudo[56198]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:27 ansible4 sudo[56342]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vdwngacyihyqlelgxyswfgomysldfqzd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380225.3230498-25480-184995856679243/AnsiballZ_copy.py
Mar 21 15:30:27 ansible4 sudo[56342]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:27 ansible4 sudo[56342]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:27 ansible4 sudo[56342]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:28 ansible4 sudo[56518]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wtxzernnksekclnbfaigfwndhusggtij ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380227.5469844-25516-156870010100926/AnsiballZ_stat.py
Mar 21 15:30:28 ansible4 sudo[56518]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:28 ansible4 sudo[56518]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:28 ansible4 sudo[56518]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:29 ansible4 sudo[56662]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ypkgiabhxbyrtlmisxhyolthijxjrpwz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380227.5469844-25516-156870010100926/AnsiballZ_copy.py
Mar 21 15:30:29 ansible4 sudo[56662]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:29 ansible4 sudo[56662]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:29 ansible4 sudo[56662]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:30 ansible4 sudo[56838]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zavhlsnngzjtduvbburfglasulcskonq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380229.3876536-25548-138483602145545/AnsiballZ_systemd.py
Mar 21 15:30:30 ansible4 sudo[56838]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:30 ansible4 sudo[56838]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:31 ansible4 sudo[56838]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:42 ansible4 sudo[57198]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bipuuxttekaozmyplhdqkwdmytlsfben ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380239.7734478-25605-257828745897728/AnsiballZ_setup.py
Mar 21 15:30:42 ansible4 sudo[57198]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:42 ansible4 sudo[57198]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:43 ansible4 sudo[57198]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:45 ansible4 sudo[57415]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vwutwqnvynvvcrlsoddcgixqeurtaelv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380243.8322802-25651-240074534801042/AnsiballZ_command.py
Mar 21 15:30:45 ansible4 sudo[57415]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:45 ansible4 sudo[57415]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:45 ansible4 sudo[57415]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:48 ansible4 sudo[57590]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jfjeftuvjvhreyfaseacfnoiurerbatf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380246.2908285-25687-244983880604370/AnsiballZ_systemd.py
Mar 21 15:30:48 ansible4 sudo[57590]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:48 ansible4 sudo[57590]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:50 ansible4 sudo[57590]: pam_unix(sudo:session): session closed for user root
Mar 21 15:30:51 ansible4 sudo[57774]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-clctelwwbodppfvtjbtqnwrobylegzgr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679380250.390095-25722-277240237164160/AnsiballZ_dnf.py
Mar 21 15:30:51 ansible4 sudo[57774]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:30:51 ansible4 sudo[57774]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:30:58 ansible4 sudo[57774]: pam_unix(sudo:session): session closed for user root
Mar 21 15:31:58 ansible4 sshd[53648]: Received disconnect from 192.168.10.10 port 49432:11: disconnected by user
Mar 21 15:31:58 ansible4 sshd[53648]: Disconnected from user ansible 192.168.10.10 port 49432
Mar 21 15:31:58 ansible4 sshd[53646]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:53:13 ansible4 sshd[58715]: Accepted publickey for ansible from 192.168.10.10 port 56632 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:53:13 ansible4 sshd[58715]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:53:15 ansible4 sudo[58926]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ikirtisbntsunvqncyzghdldlqgcecmy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381593.4291909-28383-42692415394303/AnsiballZ_setup.py
Mar 21 15:53:15 ansible4 sudo[58926]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:53:15 ansible4 sudo[58926]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:53:17 ansible4 sudo[58926]: pam_unix(sudo:session): session closed for user root
Mar 21 15:53:18 ansible4 sudo[59151]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajpafqcqfqhtmsaaxvgxvmfthleezmuk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381597.5412478-28447-240982604193343/AnsiballZ_dnf.py
Mar 21 15:53:18 ansible4 sudo[59151]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:53:18 ansible4 sudo[59151]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:53:23 ansible4 groupadd[59162]: group added to /etc/group: name=postdrop, GID=90
Mar 21 15:53:23 ansible4 groupadd[59162]: group added to /etc/gshadow: name=postdrop
Mar 21 15:53:23 ansible4 groupadd[59162]: new group: name=postdrop, GID=90
Mar 21 15:53:23 ansible4 groupadd[59168]: group added to /etc/group: name=postfix, GID=89
Mar 21 15:53:23 ansible4 groupadd[59168]: group added to /etc/gshadow: name=postfix
Mar 21 15:53:24 ansible4 groupadd[59168]: new group: name=postfix, GID=89
Mar 21 15:53:24 ansible4 useradd[59175]: new user: name=postfix, UID=89, GID=89, home=/var/spool/postfix, shell=/sbin/nologin
Mar 21 15:53:24 ansible4 useradd[59175]: add 'postfix' to group 'mail'
Mar 21 15:53:24 ansible4 useradd[59175]: add 'postfix' to shadow group 'mail'
Mar 21 15:53:28 ansible4 sudo[59151]: pam_unix(sudo:session): session closed for user root
Mar 21 15:53:30 ansible4 sudo[60576]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-stnkdelkchnzmdjhzpoyxlyuhguouwaw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381609.8727596-28479-254818001077558/AnsiballZ_dnf.py
Mar 21 15:53:30 ansible4 sudo[60576]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:53:30 ansible4 sudo[60576]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:53:36 ansible4 groupadd[60588]: group added to /etc/group: name=dovecot, GID=97
Mar 21 15:53:36 ansible4 groupadd[60588]: group added to /etc/gshadow: name=dovecot
Mar 21 15:53:36 ansible4 groupadd[60588]: new group: name=dovecot, GID=97
Mar 21 15:53:36 ansible4 useradd[60595]: new user: name=dovecot, UID=97, GID=97, home=/usr/libexec/dovecot, shell=/sbin/nologin
Mar 21 15:53:36 ansible4 groupadd[60603]: group added to /etc/group: name=dovenull, GID=974
Mar 21 15:53:36 ansible4 groupadd[60603]: group added to /etc/gshadow: name=dovenull
Mar 21 15:53:37 ansible4 groupadd[60603]: new group: name=dovenull, GID=974
Mar 21 15:53:37 ansible4 useradd[60610]: new user: name=dovenull, UID=975, GID=974, home=/usr/libexec/dovecot, shell=/sbin/nologin
Mar 21 15:53:41 ansible4 sudo[60576]: pam_unix(sudo:session): session closed for user root
Mar 21 15:53:47 ansible4 sudo[61437]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kkpgrinpiivwdqmmluitdlccypnqefxk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381626.468808-28514-10558978410144/AnsiballZ_command.py
Mar 21 15:53:47 ansible4 sudo[61437]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:53:47 ansible4 sudo[61437]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:53:48 ansible4 sudo[61437]: pam_unix(sudo:session): session closed for user root
Mar 21 15:54:48 ansible4 sshd[58717]: Received disconnect from 192.168.10.10 port 56632:11: disconnected by user
Mar 21 15:54:48 ansible4 sshd[58717]: Disconnected from user ansible 192.168.10.10 port 56632
Mar 21 15:54:48 ansible4 sshd[58715]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:55:15 ansible4 sshd[61519]: Accepted publickey for ansible from 192.168.10.10 port 42404 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:55:15 ansible4 sshd[61519]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:55:17 ansible4 sudo[61732]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kkknwmtgvnponusbxznvlwpjlmawnvaq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381715.3012571-28689-145219381730622/AnsiballZ_setup.py
Mar 21 15:55:17 ansible4 sudo[61732]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:17 ansible4 sudo[61732]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:18 ansible4 sudo[61732]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:20 ansible4 sudo[61953]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lxuycxgkgznkazixtrdbzfhjzkacbdmh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381719.3298235-28753-132443656758247/AnsiballZ_dnf.py
Mar 21 15:55:20 ansible4 sudo[61953]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:20 ansible4 sudo[61953]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:23 ansible4 sudo[61953]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:24 ansible4 sudo[62128]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-glzdsbbuxdfedkebacshbuxssljtpxtz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381723.7940445-28779-167360399001566/AnsiballZ_dnf.py
Mar 21 15:55:24 ansible4 sudo[62128]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:24 ansible4 sudo[62128]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:28 ansible4 sudo[62128]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:29 ansible4 sudo[62303]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-moomoodoyfdkxecvsoejeiuiolahinwz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381728.1340084-28805-163406611062435/AnsiballZ_get_url.py
Mar 21 15:55:29 ansible4 sudo[62303]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:29 ansible4 sudo[62303]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:29 ansible4 sudo[62303]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:37 ansible4 sudo[62534]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mymmmdfknawckvoeladwyjyriguaiyjl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381735.8690727-28843-162136692132929/AnsiballZ_command.py
Mar 21 15:55:37 ansible4 sudo[62534]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:37 ansible4 sudo[62534]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:38 ansible4 sudo[62534]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:54 ansible4 sudo[62765]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gzwrvnpgwefozukelzrxogwicyvtgjaa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381751.9681845-28880-2901646026903/AnsiballZ_setup.py
Mar 21 15:55:54 ansible4 sudo[62765]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:54 ansible4 sudo[62765]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:55 ansible4 sudo[62765]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:57 ansible4 sudo[62982]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-egumexrietfaifqhlxzpbjtdqywppyyx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381756.3232946-28926-97025336612034/AnsiballZ_dnf.py
Mar 21 15:55:57 ansible4 sudo[62982]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:57 ansible4 sudo[62982]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:56:01 ansible4 sudo[62982]: pam_unix(sudo:session): session closed for user root
Mar 21 15:56:02 ansible4 sudo[63157]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zufjkgycynppxwnssriaglzthlnlffwf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381761.5109851-28948-246913835339080/AnsiballZ_get_url.py
Mar 21 15:56:02 ansible4 sudo[63157]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:56:02 ansible4 sudo[63157]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:56:03 ansible4 sudo[63157]: pam_unix(sudo:session): session closed for user root
Mar 21 15:57:03 ansible4 sshd[61521]: Received disconnect from 192.168.10.10 port 42404:11: disconnected by user
Mar 21 15:57:03 ansible4 sshd[61521]: Disconnected from user ansible 192.168.10.10 port 42404
Mar 21 15:57:03 ansible4 sshd[61519]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:59:18 ansible4 sshd[63294]: Accepted publickey for ansible from 192.168.10.10 port 36148 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 15:59:18 ansible4 sshd[63294]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:59:20 ansible4 sudo[63505]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-plchtznogpmnitjocqsmmiiezlbcaiiq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381958.4642673-29324-34115996951598/AnsiballZ_setup.py
Mar 21 15:59:20 ansible4 sudo[63505]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:59:20 ansible4 sudo[63505]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:59:22 ansible4 sudo[63505]: pam_unix(sudo:session): session closed for user root
Mar 21 15:59:23 ansible4 sudo[63723]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pptnyjtrruoeqtcnmacnhyqlwzmveeba ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381962.3362014-29391-248693702541479/AnsiballZ_dnf.py
Mar 21 15:59:23 ansible4 sudo[63723]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:59:23 ansible4 sudo[63723]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:59:27 ansible4 sudo[63723]: pam_unix(sudo:session): session closed for user root
Mar 21 15:59:28 ansible4 sudo[63898]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-npkqvxisiixxjktpwxfmzeyhqsbgixoc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381967.2422397-29415-95952368250815/AnsiballZ_dnf.py
Mar 21 15:59:28 ansible4 sudo[63898]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:59:28 ansible4 sudo[63898]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:59:31 ansible4 sudo[63898]: pam_unix(sudo:session): session closed for user root
Mar 21 15:59:32 ansible4 sudo[64073]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-psobrqfbuptjqnctyjjwopgydlqoofep ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381971.832473-29439-77064591010897/AnsiballZ_get_url.py
Mar 21 15:59:32 ansible4 sudo[64073]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:59:32 ansible4 sudo[64073]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:59:33 ansible4 sudo[64073]: pam_unix(sudo:session): session closed for user root
Mar 21 16:00:33 ansible4 sshd[63296]: Received disconnect from 192.168.10.10 port 36148:11: disconnected by user
Mar 21 16:00:33 ansible4 sshd[63296]: Disconnected from user ansible 192.168.10.10 port 36148
Mar 21 16:00:33 ansible4 sshd[63294]: pam_unix(sshd:session): session closed for user ansible
Mar 21 16:04:40 ansible4 sshd[64236]: Accepted publickey for ansible from 192.168.10.10 port 48360 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 16:04:40 ansible4 sshd[64236]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 16:04:42 ansible4 sudo[64462]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-droyzoolzfxcbrvdcxttbwknerulxbxx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382280.4222865-29713-128347122133175/AnsiballZ_setup.py
Mar 21 16:04:42 ansible4 sudo[64462]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:04:42 ansible4 sudo[64462]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:04:44 ansible4 sudo[64462]: pam_unix(sudo:session): session closed for user root
Mar 21 16:04:45 ansible4 sudo[64681]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-glgkzgohmuyevwzsfcmpmzjhzgnwlayc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382284.6242015-29774-101932381769719/AnsiballZ_dnf.py
Mar 21 16:04:45 ansible4 sudo[64681]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:04:45 ansible4 sudo[64681]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:04:49 ansible4 sudo[64681]: pam_unix(sudo:session): session closed for user root
Mar 21 16:04:49 ansible4 sudo[64856]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jlsdslfgcgsysipqryaerohcpnpmkvcs ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382289.0613384-29796-235429618875887/AnsiballZ_dnf.py
Mar 21 16:04:49 ansible4 sudo[64856]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:04:49 ansible4 sudo[64856]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:04:53 ansible4 sudo[64856]: pam_unix(sudo:session): session closed for user root
Mar 21 16:04:54 ansible4 sudo[65031]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fwfvnnlfnanaclppmaairnerjgamzzag ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382293.2987385-29819-32366875835933/AnsiballZ_get_url.py
Mar 21 16:04:54 ansible4 sudo[65031]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:04:54 ansible4 sudo[65031]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:04:54 ansible4 sudo[65031]: pam_unix(sudo:session): session closed for user root
Mar 21 16:05:50 ansible4 sudo[65282]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xzopiwtsekdmwclgobssqyzjquqkbkjd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382347.8147256-29934-111983425926117/AnsiballZ_setup.py
Mar 21 16:05:50 ansible4 sudo[65282]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:05:50 ansible4 sudo[65282]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:05:52 ansible4 sudo[65282]: pam_unix(sudo:session): session closed for user root
Mar 21 16:05:53 ansible4 sudo[65501]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bgjcacztnzrxlpsftydfvukmyhwwmqqd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382352.7438416-29986-203450012659777/AnsiballZ_dnf.py
Mar 21 16:05:53 ansible4 sudo[65501]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:05:53 ansible4 sudo[65501]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:05:58 ansible4 sudo[65501]: pam_unix(sudo:session): session closed for user root
Mar 21 16:05:59 ansible4 sudo[65676]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sfhezlivuoqtapxnuqbsqpipnnwqqdqm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382358.3022435-30008-60484927842487/AnsiballZ_get_url.py
Mar 21 16:05:59 ansible4 sudo[65676]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:05:59 ansible4 sudo[65676]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:06:00 ansible4 sudo[65676]: pam_unix(sudo:session): session closed for user root
Mar 21 16:06:09 ansible4 sudo[65915]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hxzpikcgokmcqacploisqrogziazvjmt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382366.5185003-30040-149829859267380/AnsiballZ_setup.py
Mar 21 16:06:09 ansible4 sudo[65915]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:06:09 ansible4 sudo[65915]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:06:10 ansible4 sudo[65915]: pam_unix(sudo:session): session closed for user root
Mar 21 16:06:12 ansible4 sudo[66132]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vvmdrhxdggsyczerztskbgipqfexdjtb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382371.0720844-30085-169699629322816/AnsiballZ_dnf.py
Mar 21 16:06:12 ansible4 sudo[66132]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:06:12 ansible4 sudo[66132]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:06:15 ansible4 sudo[66132]: pam_unix(sudo:session): session closed for user root
Mar 21 16:06:20 ansible4 sudo[66372]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-snwuectvpxxojvpfyjiasgwwzqnemdic ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382379.609721-30121-209862963538527/AnsiballZ_command.py
Mar 21 16:06:20 ansible4 sudo[66372]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:06:20 ansible4 sudo[66372]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:06:22 ansible4 sudo[66372]: pam_unix(sudo:session): session closed for user root
Mar 21 16:07:22 ansible4 sshd[64238]: Received disconnect from 192.168.10.10 port 48360:11: disconnected by user
Mar 21 16:07:22 ansible4 sshd[64238]: Disconnected from user ansible 192.168.10.10 port 48360
Mar 21 16:07:22 ansible4 sshd[64236]: pam_unix(sshd:session): session closed for user ansible
Mar 21 16:09:13 ansible4 sshd[66482]: Accepted publickey for ansible from 192.168.10.10 port 36674 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 16:09:13 ansible4 sshd[66482]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 16:09:15 ansible4 sudo[66704]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jrgmfxdsdlawkbiqbjeumiwrptuqcwpb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382553.3171294-30394-62746329458909/AnsiballZ_setup.py
Mar 21 16:09:15 ansible4 sudo[66704]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:09:15 ansible4 sudo[66704]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:09:17 ansible4 sudo[66704]: pam_unix(sudo:session): session closed for user root
Mar 21 16:09:19 ansible4 sudo[66929]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-warxbzcrqzgimhzqjbtutrsfyejtheem ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382557.4480612-30460-11838525490925/AnsiballZ_systemd.py
Mar 21 16:09:19 ansible4 sudo[66929]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:09:19 ansible4 sudo[66929]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:09:19 ansible4 sudo[66929]: pam_unix(sudo:session): session closed for user root
Mar 21 16:09:21 ansible4 sudo[67109]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hggqsrsjcebwcemjbcjqpbwljstwgmjk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382560.106553-30498-111314602546850/AnsiballZ_dnf.py
Mar 21 16:09:21 ansible4 sudo[67109]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:09:21 ansible4 sudo[67109]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:09:29 ansible4 sudo[67109]: pam_unix(sudo:session): session closed for user root
Mar 21 16:10:28 ansible4 sudo[67870]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-djhuajmlxgqlbmhwleeugebyrxoaqdwq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382627.5775785-30667-214091495737278/AnsiballZ_command.py
Mar 21 16:10:28 ansible4 sudo[67870]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:10:28 ansible4 sudo[67870]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:10:30 ansible4 sudo[67870]: pam_unix(sudo:session): session closed for user root
Mar 21 16:10:36 ansible4 sudo[68101]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zvuvipyyqqvagcovogrkrssemnttlogv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382633.706066-30715-45486523874999/AnsiballZ_setup.py
Mar 21 16:10:36 ansible4 sudo[68101]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:10:36 ansible4 sudo[68101]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:10:36 ansible4 sudo[68101]: pam_unix(sudo:session): session closed for user root
Mar 21 16:10:40 ansible4 sudo[68331]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ulqaipuqsthykwviacsrhuoghrblyxkx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382638.9556932-30775-207870977181794/AnsiballZ_setup.py
Mar 21 16:10:40 ansible4 sudo[68331]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:10:40 ansible4 sudo[68331]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:10:42 ansible4 sudo[68331]: pam_unix(sudo:session): session closed for user root
Mar 21 16:10:43 ansible4 sudo[68549]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rwbgovuvyvcqmhyxntnkoagnaoiogahk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382642.7344928-30820-129268167667007/AnsiballZ_dnf.py
Mar 21 16:10:43 ansible4 sudo[68549]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:10:43 ansible4 sudo[68549]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:10:47 ansible4 useradd[68559]: failed adding user 'postfix', exit code: 9
Mar 21 16:10:51 ansible4 sudo[68549]: pam_unix(sudo:session): session closed for user root
Mar 21 16:10:52 ansible4 sudo[69948]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ghlqihdsheqvkpolfyacoqomoiyipzji ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382651.3056278-30842-107619179224492/AnsiballZ_dnf.py
Mar 21 16:10:52 ansible4 sudo[69948]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:10:52 ansible4 sudo[69948]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:10:59 ansible4 sudo[69948]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:00 ansible4 sudo[70722]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-aylhixxurblochvxcuaviuetdbxrhslw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382659.1642416-30864-91515316661841/AnsiballZ_get_url.py
Mar 21 16:11:00 ansible4 sudo[70722]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:00 ansible4 sudo[70722]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:00 ansible4 sudo[70722]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:01 ansible4 sudo[70898]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vkvhcnvqyaazckbhhkckrxqegxicsegf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382660.7204409-30882-210987113339429/AnsiballZ_systemd.py
Mar 21 16:11:01 ansible4 sudo[70898]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:01 ansible4 sudo[70898]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:03 ansible4 sudo[70898]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:04 ansible4 sudo[71165]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lgzwhovvtvdoesgzkwznkfzrfyurnzew ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382663.2398732-30900-183055870526263/AnsiballZ_systemd.py
Mar 21 16:11:04 ansible4 sudo[71165]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:04 ansible4 sudo[71165]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:04 ansible4 sudo[71165]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:08 ansible4 sudo[71418]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-juwxkgqbnurbnaatfxfcytfqzgruvijj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382667.7776105-30929-49023722605038/AnsiballZ_command.py
Mar 21 16:11:08 ansible4 sudo[71418]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:08 ansible4 sudo[71418]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:10 ansible4 sudo[71418]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:15 ansible4 sudo[71651]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jaggwajtovfcftklhebsunhlssidfemm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382673.156687-30965-176183048541374/AnsiballZ_setup.py
Mar 21 16:11:15 ansible4 sudo[71651]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:15 ansible4 sudo[71651]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:16 ansible4 sudo[71651]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:19 ansible4 sudo[71877]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-syvldyxnqoyqbmmckrqzscfhmzlxbqvm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382677.3058329-31011-218625206697944/AnsiballZ_systemd.py
Mar 21 16:11:19 ansible4 sudo[71877]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:19 ansible4 sudo[71877]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:20 ansible4 sudo[71877]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:23 ansible4 sudo[72073]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xivxwbsjlmvjseelztvlgnmxbolawppf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382681.4062946-31052-227174899798485/AnsiballZ_dnf.py
Mar 21 16:11:23 ansible4 sudo[72073]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:23 ansible4 sudo[72073]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:32 ansible4 sudo[72073]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:35 ansible4 sudo[72817]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rdlpcyewxwutlrjxpusifsuabtxmizqv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382694.8011281-31111-247158929732602/AnsiballZ_command.py
Mar 21 16:11:35 ansible4 sudo[72817]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:35 ansible4 sudo[72817]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:37 ansible4 sudo[72817]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:42 ansible4 sudo[73048]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zqahegldimppgpkbyuvhaatrngnpxyyh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382701.5140285-31147-4578845131118/AnsiballZ_command.py
Mar 21 16:11:42 ansible4 sudo[73048]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:42 ansible4 sudo[73048]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:43 ansible4 sudo[73048]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:49 ansible4 sudo[73279]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ttufplnqzpkpemdhptqukwudgnhwuaom ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382707.038707-31184-46211516515377/AnsiballZ_setup.py
Mar 21 16:11:49 ansible4 sudo[73279]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:49 ansible4 sudo[73279]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:50 ansible4 sudo[73279]: pam_unix(sudo:session): session closed for user root
Mar 21 16:11:51 ansible4 sudo[73496]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xaqlavfuxxtnqtwcxkapurdzyqaaqdhv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382710.9072547-31230-246086396349668/AnsiballZ_dnf.py
Mar 21 16:11:51 ansible4 sudo[73496]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:11:51 ansible4 sudo[73496]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:11:55 ansible4 useradd[73506]: failed adding user 'postfix', exit code: 9
Mar 21 16:11:59 ansible4 sudo[73496]: pam_unix(sudo:session): session closed for user root
Mar 21 16:12:00 ansible4 sudo[74895]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mnflymfressasvzbftpkmgehwxixnqel ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382719.6732774-31252-72522556268056/AnsiballZ_dnf.py
Mar 21 16:12:00 ansible4 sudo[74895]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:12:00 ansible4 sudo[74895]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:12:07 ansible4 sudo[74895]: pam_unix(sudo:session): session closed for user root
Mar 21 16:12:08 ansible4 sudo[75685]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gwlaerzskgbbizqdvwdxdhsidkmizzim ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382727.5800397-31275-168967589775402/AnsiballZ_get_url.py
Mar 21 16:12:08 ansible4 sudo[75685]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:12:08 ansible4 sudo[75685]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:12:09 ansible4 sudo[75685]: pam_unix(sudo:session): session closed for user root
Mar 21 16:12:10 ansible4 sudo[75861]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yxjsitxxsdvlbmsbqrxixwkxtosaveip ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382729.0839205-31292-57439147808749/AnsiballZ_systemd.py
Mar 21 16:12:10 ansible4 sudo[75861]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:12:10 ansible4 sudo[75861]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:12:11 ansible4 sudo[75861]: pam_unix(sudo:session): session closed for user root
Mar 21 16:12:12 ansible4 sudo[76120]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uvlcwrcffhawbwnnrwtpvjxubqqykldn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679382731.6405199-31310-52149835037375/AnsiballZ_systemd.py
Mar 21 16:12:12 ansible4 sudo[76120]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:12:12 ansible4 sudo[76120]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:12:13 ansible4 sudo[76120]: pam_unix(sudo:session): session closed for user root
Mar 21 16:13:13 ansible4 sshd[66485]: Received disconnect from 192.168.10.10 port 36674:11: disconnected by user
Mar 21 16:13:13 ansible4 sshd[66485]: Disconnected from user ansible 192.168.10.10 port 36674
Mar 21 16:13:13 ansible4 sshd[66482]: pam_unix(sshd:session): session closed for user ansible
Mar 21 16:58:30 ansible4 sshd[77132]: Accepted publickey for ansible from 192.168.10.10 port 44526 ssh2: RSA SHA256:r5ny2RLfd/Dq3yuyZB8n46R2Q5dhCIPtB5aS+T2CPdg
Mar 21 16:58:30 ansible4 sshd[77132]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 16:58:34 ansible4 sudo[77350]: ansible : TTY=pts/0 ; PWD=/home/ansible/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yrmcsilmlewayanbvzjaqrxbbrugnllx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385510.7309115-33215-258386402200048/AnsiballZ_setup.py
Mar 21 16:58:34 ansible4 sudo[77350]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:58:34 ansible4 sudo[77350]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:58:36 ansible4 sudo[77350]: pam_unix(sudo:session): session closed for user root
